### ISSUE TITLE
Using slots for collecting parameter to be passed through rendering

### ISSUE THREAD

**Issue by romaricpascal** [ViewComponent/view_component#1020]
## Feature request
It'd be great if slots could be used to only collect arguments and let the component decide how to use them, alongside their current behaviour of automatically rendering components to strings. This allow these arguments to be forwarded to slots of internal components. 

### Motivation

As an example, I'm trying to build a navigation menu with nested navigation items. I'd like to provide the following API:

```erb
<%= render NavigationMenuComponent do |menu| %>
  <% menu.item(label: 'Item 1', href: '') %>
  <% menu.item(label: 'Item 2', href: '') do |item| %>
  	<% item.child(label: 'Child 1', href: '') %>
  	<% item.child(label: 'Child 2', href: '') %>
  <% end %>
<% end %>
```

The first level is achieved with the current version of SlotsV2 through:

```rb
class NavigationMenuComponent < ViewComponent::Base
  include ViewComponent::SlotableV2

  renders_many :items, NavigationItemComponent
end
```

The nested items however need to be rendered withing their own `NavigationMenuComponent`, rendered in the `NavigationItemComponent`'s template. But the API I'd like to provide is a `renders_many :children` rather than a `renders_one :submenu, NavigationMenuComponent`.

I've been able to work around it using:

```rb
class NavItemComponent < ViewComponent::Base

  include ViewComponent::SlotableV2

  renders_many :children, -> (**attributes) do
    attributes
  end
end
```

and within the template

```erb
<% if children.any? %>
  <%= render NavMenuComponent.new do |menu| %>
    <% children.each do |child| %>
      <% menu.item(**child.instance_variable_get(:@_content)) %>
    <% end %>
  <% end %>
<% end %>
```

It'd be great if there was an abstraction over that, maybe only a public accessor for the `@_content` instance variable. But maybe I've missed something in the documentation about it?

**Comment by jonspalmer** [comment]
I think you have two options. First just render the sub nav as the content of the item:

```erb
<%= render NavigationMenuComponent do |menu| %>
  <% menu.item(label: 'Item 1', href: '') %>
  <% menu.item(label: 'Item 2', href: '') do |item| %>
    <%= render NavigationMenuComponent do |sub_menu| %>      
  	<% sub_menu.item(label: 'Child 1', href: '') %>
  	<% sub_menu.item(label: 'Child 2', href: '') %>
    <% end %>
  <% end %>
<% end %>
```

I'm not sure you even need a NavigationItemComponent at this point but either way you can just use `content` in the template.


My other thought would be do you need slots at all? Unless you need view helpers for the content of the nav you could just pass it all as data. I've built this as:

```ruby
# in controller logic
@nav_items = [
  { label: 'Item1', href: ''},
  { 
    label: 'Item1',
    href: '',
    children: [
      { label: 'Child1', href: ''},
      { label: 'Child2', href: ''},
    ]
  }
]
```

and in the view
```erb
<%= render NavigationMenuComponent(items: @items) %>
```

With this approach you likely get infinite levels of nav nesting too as your NavigationMenuComponent template is just recursive. ie somewhere in the template you do

```erb
<% if children.any? %>
  <%= render NavMenuComponent.new(items: children) %>
<% end %>
```

**Comment by romaricpascal** [comment]
Cheers, I completely hadn't thought of passing the children to the `NavMenuComponent` through an `items` attribute. That made everything much tidier.

**Comment by joelhawksley** [comment]
I agree with @jonspalmer's response 👍🏻

**Comment by Spone** [comment]
I'll go ahead and close this issue. Feel free to reply if you want to add something!
