### ISSUE TITLE
[Feature request] Public variant setter API for ViewComponent class

### ISSUE THREAD

**Issue by HipsterBrown** [ViewComponent/view_component#1034]
## Feature request
Expose a class method for setting a variant from the class definition, as an alternative to the `with_variant` method. _Inspired by the recent `with_collection_parameter` addition_

```rb
class MyViewComponent < ViewComponent::Base
  with_variant_parameter: :name

  def initialize(name:)
    @name = name
  end
end
```

### Motivation

My team is currently adopting ViewComponent for the Rails implementation of our design system, replacing our in-house `Component` class modeled after `komponent`. We have an `IconViewComponent` that is using an internal API in order to treat icons as a variant of the base component, creating a template variant for each: `icon_view_component.html+checkmark.erb` for example

Rather than have consumers of this component use the public `with_variant` method, the component initializer is setting the `name` attr as `@__vc_variant` (formerly `@variant` before v2.35.0). 

```rb
render IconViewComponent.new(name: :checkmark, color: 'green')
```

instead of

```rb
render IconViewComponent.new(color: 'green').with_variant(:checkmark)
```

It's a subtle difference for usage but makes a difference in semantics how `variant` is used elsewhere in the component library, i.e. a `primary` variant for a button component.

**Comment by joelhawksley** [comment]
@HipsterBrown thanks for taking the time to file this issue! 

I think that we could do a better job documenting what variants should be used for, but they are coupled to Action Pack variants: https://viewcomponent.org/guide/testing.html#action-pack-variants.

I think that others have solved a similar problem to yours via branching logic in a single component template:

```erb
<% case name %>
<% when :checkmark %>

<% when :close %>

<% end %>
```

**Comment by boardfish** [comment]
I was using variants in this way in #954, so it might be helpful to you to read the issue history there to see where we got to. 

To add to Joel's solution, you could even make the variants new components in their own right. The structure I'd suggest here would be to:

- have a base `IconViewComponent` class
- create a new class under the `IconViewComponent` namespace for each variant you've introduced, e.g. `icon_view_component/checkmark.rb`, that inherits from that class. 
- copy your templates over to the corresponding location, e.g. `mv icon_view_component.html+checkmark.erb icon_view_component/checkmark/checkmark.html.erb`
- remove your variants from the initializers and render these classes instead. 

Any that you don't provide a template for will fall back to the template for the base class. 

Hope this is helpful to you!

**Comment by HipsterBrown** [comment]
Thanks for the quick responses and context! I should have provided a bit more details about the amount of icons we're generating from source files 😅 We currently have just over _500_ icon templates that account for the various sizes of each icon type.

That basically rules out the single component template since it would be an absolutely massive file, even if it was auto-generated. The subclass approach could be possible (and be easier to migrate towards as described) but would definitely increase the complexity of using the icon system. One advantage is the similarity of implementation for our React library which generates individual components for each icon. 

The proposed solution is definitely flexing the original intention for Action Pack variants, which was how we figured out the `.html+name.erb` file format worked with ViewComponent. 💯 

My team and I have looked at the way Octicons works with so many icons (https://github.com/primer/octicons/tree/main/lib/octicons_gem), which appears to be unique from the ViewComponent workflow.

**Comment by boardfish** [comment]
Hey Nick, apologies that I haven't gotten around to checking this out in more detail. As you might've seen, `with_variant` is being deprecated, but I feel like the external API for it could definitely inspire your approach. Maybe something like `IconComponent.new(...).with_icon(:icon_name)` could be something to aim for. If you could provide a little more detail on what your current approach is and what you might be aiming for, it could help us to reach a solution here.

**Comment by HipsterBrown** [comment]
@boardfish No worries! I just read through the mentioned issue and associated PR to deprecated `with_variant`. That makes sense, given the confusion about when it should be used; however, to replace this API, we'd still need a way of selecting the correct template to render based on the initializer args or a public method like `with_icon`. 

This is the current component class:

```rb
class IconViewComponent < ViewComponent::Base
  attr_reader :svg_aria_label, :svg_aria_hidden, :svg_role_img, :name

  def initialize(
    name:,
    color: nil,
    alt_text: '',
    classes: nil
  )
    @name = name
    # ViewComponent::Base uses this internally to select variant template
    @__vc_variant = name
    @color = color
    @alt_text = alt_text
    @classes = classes

    @svg_aria_label = alt_text.presence
    @svg_aria_hidden = alt_text.blank?
    @svg_role_img = alt_text.present?
  end

  def classes
    value = [@classes]
    value << "u-color-#{@color}" if @color.present?
    value.compact.join(' ')
  end

  def title_element
    @alt_text.present? ? content_tag(:title, @alt_text) : nil
  end
end
```

With the file system looking something like this:

```
app/components/
  icon_view_component.rb
  icon_view_component/
    icon_view_component.html+arrow_circle.erb
    icon_view_component.html+checkmark.erb
    // a _lot_ more variant template files
    icon_view_component.html.erb
```

So is there a current (or planned) way to conditionally pick a template file when rendering a component that doesn't use variants?

**Comment by joelhawksley** [comment]
@HipsterBrown @boardfish this has question has some echoes of @fsateler's proposal in https://github.com/github/view_component/pull/451. Perhaps you all could chat about a proposed API?

**Comment by barmintor** [comment]
As a ViewComponent adopter, I have to confess that I don't understand the position that variants are being misused in their current (deprecated) iteration. The method of overriding is clunky, and I definitely understand not wanting manipulation of the variants list in the `@view_context` to bleed out of a component - but their usage otherwise seems to comport with the documented use case at ActionView, especially if localization is understood as a separate feature. And branching logic in the template seems like a significant step backwards - the general simplification of erb templates in our app has been a selling point for my team.

In general (and obviously IMO), ViewComponent shines when it is able to be "Rails, faster, with verifiable local context". Adding entirely new AP, as in #451, for something that is conceptually like variants seems like a step away from that? Whereas the existing API is (again, IMO) a "least surprising" approach. Would maybe a `with_details` API that shimmed the existing view context split the difference?

I also obviously can't figure out what the best of several issues is to comment on this, sorry if this is stale!

**Comment by fsateler** [comment]
Please, don't confuse #451 with variants. The primary focus of that PR is refactoring: sometimes you want multiple methods in a single class. Same happens when the method is defined via an ERB template.

**Comment by BlakeWilliams** [comment]
Thanks for opening this issue!

The core team has chatted about variants a good few times and the general consensus is that ViewComponent should be compatible with [Rails variants](https://guides.rubyonrails.org/layouts_and_rendering.html#the-variants-option), but not extend them for other use cases. We found that variants were being used in ways that were incompatible, and fundamentally different from the Rails variant functionality and decided to remove the ability to allow consumers to set a specific variant on individual components.

The current recommendation is to use Rails hooks as [mentioned in the docs](https://guides.rubyonrails.org/layouts_and_rendering.html#the-variants-option) to set the current variant for the entire request which aligns the feature more closely to the intention of our variant implementation and the Rails functionality.
