### ISSUE TITLE
turbo_frame_tag inside a component duplicates it

### ISSUE THREAD

**Issue by pacMakaveli** [ViewComponent/view_component#1099]
Ok, so I'm not sure if the title makes sense. Hopefully the code will.

When rendering a component which has a `turbo_frame_tag` inside it, ViewComponent (or Turbo?) will render the contents twice.
Once inside a `turbo_frame_tag` as expected, and again, with whatever's inside the `turbo_frame_tag`

Note: The content of the component html doesn't matter from my testing. I initially thought it might be another turbo frame tag or component conflicting, since my VC is quite complex.

```
- achievements.each do |achievement|
  = turbo_frame_tag(achievement.event) do
    = render(Provider::TrophyComponent.new(trophy: achievement))
```
```
= turbo_frame_tag(@trophy) do

  .cell-auto.card.--with-image data-controller='provider--trophy-component--trophy-component' id=dom_id(@trophy)
    .row.items-stretch
      .cell-auto.card class="#{ @trophy.cover.attached? ? '' : 'animate-pulse' } #{ @trophy.is_a?(XBOX::Trophy) ? 'w-60' : 'w-38' }"
        = helpers.lazy_image_tag(@trophy.cover, class: 'w-full h-full rounded-md object-cover') if @trophy.cover.attached?
```
<img width="1420" alt="Screenshot 2021-10-19 at 13 27 20" src="https://user-images.githubusercontent.com/894272/137909459-797480d3-0928-45e6-b588-d7c79f68589e.png">

To fix this, I have to extract the component inside a rails partial and wrap it inside a turbo_frame_tag in there, instead of the VC.

```
- achievements.each do |achievement|

  = turbo_frame_tag(achievement.event) do
    = render(partial: 'fix', locals: { achievement: achievement }, cache: false)
```
```
= turbo_frame_tag(achievement.event) do
  = render(Provider::TrophyComponent.new(trophy: achievement))
```
### Expected behavior
The ViewComponent shouldn't render the contents twice.

### System configuration
**Rails version**:
ruby -Rails 6.1.4.1
**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
**Gem version**:
  view_component (2.40.0)
  turbo-rails (7.1.0)

**Comment by boardfish** [comment]
Hey @pacMakaveli! It'd be really helpful if you could provide us with a failing test case or a replica of the issue. If you want to get started with the latter, I'd recommend doing the following:

```
rails new --minimal view_component-1099
cd view_component-1099
bundle add view_component
rails g component TurboFrameTag
```

A failing test case is preferable, but either way, a replica of the issue in isolation will be helpful in diagnosing it. Thanks!

**Comment by HashNotAdam** [comment]
> Would calling `helpers.turbo_frame_tag` instead of `turbo_frame_tag` fix this in the short term?

Afraid not, however, @xkraty's solution works a treat.
Either:
```html
<turbo-frame id="some_id">
  Some content
</turbo-frame>
```
Or:
```ruby
<%= tag.turbo_frame(id: "some_id") do %>
  Some content
<% end %>
```

**Comment by swanson** [comment]
Adding `include Turbo::FramesHelper` in your component class seems to work as well: you can then call `turbo_frame_tag` directly instead of proxying through `helpers`

**Comment by pacMakaveli** [comment]
@swanson it didn't work for me. Nor did the `helpers.turbo_frame_tag`
However, @HashNotAdam's solution works a treat! Thanks a bunch to everyone that chimed in.

So, if you have issues with the ViewComponent duplicating your content, or messing with the HTML rendering, `tag.turbo_frame` fixes it.

**Comment by joelhawksley** [comment]
@pacMakaveli mind writing a docs PR to reflect this?

**Comment by stex** [comment]
The same happened for me after upgrading from `haml` 5 to 6.  
Using `tag.turbo_frame` fixed it for me.

**Comment by a-nickol** [comment]
As far as I can see, the reason is, that the content of the tag rendered outside of the tag instead inside of it. This results in a duplication of the content since it is not replaced by turbo but technically appended.

**Comment by Petercopter** [comment]
*bump* 
@HashNotAdam thanks for the workaround 👍 🎉
