### ISSUE TITLE
CHANGELOG.md looks like an empty file without any links

### ISSUE THREAD

**Issue by gambala** [ViewComponent/view_component#1170]
## Feature request

Ability to view actual changelogs within a one click

### Motivation

Tools like [gem_updater](https://github.com/MaximeD/gem_updater) show links to changelogs for updated gems in a bundle, but every time I go to these links for ViewComponent, I see an empty CHANGELOG.md without any links but with text "docs/CHANGELOG.md". And it's so uncomfortable to search and navigate to actual changelogs every time

I see that CHANGELOG.md file is actually a symlink, but sadly github.com UI doesn't respond to it correctly (it would be nice to just click the text inside and go straight to CHANGELOG.md in docs folder)

Another possible solution I see is changing the CHANGELOG.md's text and add a link here:

1. Maybe to https://github.com/github/view_component/releases (because I see all changelogs there too)
2. Or to a website https://viewcomponent.org/CHANGELOG.html

So, what do you think?

**Comment by boardfish** [comment]
I agree it's a bit strange that CHANGELOG.md isn't in the root, and I've fallen foul of the same thing a fair few times. Semantically, yes, the changelog is a document, but for the sake of accessibility, I agree that folks will more intuitively look at the root of the repo to find it. I'd be happy for the current arrangement to be switched (i.e. /docs symlinks to /).

**Comment by Spone** [comment]
> I agree that folks will more intuitively look at the root of the repo to find it. I'd be happy for the current arrangement to be switched (i.e. /docs symlinks to /).

I think there was a problem with that setup when generating the docs, if I remember correctly @joelhawksley?

**Comment by joelhawksley** [comment]
@Spone that's correct. Jekyll wasn't playing nicely with a symlink in the opposite direction. 

I'd be open to changing the docs site to just link to CHANGELOG.md on `main` on GitHub if you'd like to do that @gambala ❤️

**Comment by gambala** [comment]
Nice example of how to fix the issue with just a link to an actual logs: https://github.com/ruby-i18n/i18n/blob/master/CHANGELOG.md
