### ISSUE TITLE
allowed_queries in documentation but not in code

### ISSUE THREAD

**Issue by hjhart** [ViewComponent/view_component#1288]
When browsing through the documentation, you can see that `allowed_queries` is an API that expected to be exposed. It is something that GitHub uses extensively in their test suite, as far as I've heard.

However, when searching through the repository, you can only see references to it in documentation, but not code.

<img width="1291" alt="Screen Shot 2022-02-17 at 11 15 08 AM" src="https://user-images.githubusercontent.com/547981/154554164-d6b79ecb-7240-405e-90a6-f501b6a1162c.png">

Is there some library that we're missing in order to utilize this?

**Comment by dmarcoux** [comment]
In the [slides](https://github.com/joelhawksley/identity/blob/b7b71a75c7baa8877309ad35daed8dda200bc837/talks/2021/slides.md) from the talk _ViewComponents in the real world_ held by @joelhawksley, I've found the following code under the [Performance](https://github.com/joelhawksley/identity/blob/b7b71a75c7baa8877309ad35daed8dda200bc837/talks/2021/slides.md#performance) section:

```ruby
def render_inline(component, allowed_queries: 0)
  assert_query_counts(allowed_queries) do
    super(component)
  end
end
```

With this text:

> So to help developers understand how their view code might interact with the database. We redefined the helper used to render ViewComponent in unit tests. To accept a number of allowed queries, defaulting to zero allowed. We then render the component, failing the test if the actual number of queries doesn't match what was expected. This helper has turned out to be quite educational. It's helped us better understand the side affects of our code and prevented the introduction of several N+1 queries.

I wonder if this should be included by default in the `view_component` gem. What do you think?

**Comment by camertron** [comment]
Hey @dmarcoux, thanks for bringing this up. We talked about it internally today and decided we should consider upstreaming it into either view_component or even Rails. One of us will update this issue when we have the time to make some progress.

**Comment by hjhart** [comment]
@camertron @joelhawksley Any updates on this one? Anything I can do to help? (Likely not, since I'm external to GitHub, but figured I'd ask anyway).

**Comment by hjhart** [comment]
Sorry to be a pest, but curious what the latest on this might be? Totally fine if the answer is "no update" @camertron @joelhawksley

**Comment by joelhawksley** [comment]
@hjhart no updates. I'd be happy to pair with you on getting it started if you'd like to take it on, but IMO it should go into Rails, not ViewComponent.

**Comment by fwolfst** [comment]
I have also seen code or tutorial suggesting that it is possible to alert e.g. in dev environment when a rendering view_component initializes db hits. I am pretty sure that it was not this `render_inline` but a configuration value. Cannot find it anymore though. 👀

**Comment by pdud** [comment]
Here is a blog post from Evil Martians with a way how to do this. It's under the Runtime Linters section.

https://evilmartians.com/chronicles/viewcomponent-in-the-wild-supercharging-your-components#runtime-linters

**Comment by joelhawksley** [comment]
@hjhart it looks like @p8 landed this feature in Rails! https://github.com/rails/rails/pull/50281

I'm going to close this issue ❤
