### ISSUE TITLE
Mention version info in docs

### ISSUE THREAD

**Issue by camertron** [ViewComponent/view_component#1313]
In the docs, it would be cool to mention the version of view_component certain features were introduced in.

**Comment by Spone** [comment]
Also, we could mention the latest version of the gem on the landing page, after we merge #1151.

Something like this:

![image](https://user-images.githubusercontent.com/38524/158859258-5e2bbf19-57a2-47f6-b740-971c907cba54.png)

**Comment by swanson** [comment]
This would be very helpful. On two separate occasions I've been looking at the VC docs site and trying to use features only to realize my version of the gem was not new enough.
