### ISSUE TITLE
Using components as view/page template

### ISSUE THREAD

**Issue by stephannv** [ViewComponent/view_component#1412]
## Feature request

Any plans to support ViewComponent usage as a view/page template?

The docs says:

> It’s also possible to render ViewComponents in controllers:

```ruby
# app/controllers/home_controller.rb
def show
  render(ExampleComponent.new(title: "My Title")) { "Hello, World!" }
end
```

So I tried to do something like this:
```ruby
# app/pages/posts/index_page.rb
class Posts::IndexPage < ViewComponent::Base
  def initialize(posts:)
    @posts = posts
  end
end

# app/pages/posts/index_page.html.erb
<h1><%= t(".title") %></h1>

<% @posts.each do |post| %>
   <%= render Posts::CardComponent.new(post: post)
<% end %>

# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    posts = Post.all
    
    render Posts::IndexPage.new(posts: posts)  
  end
end
```

It worked but the experience can be improved:
-  The i18n doesn't work well because the i18n_scope/virtual_path uses `view_component_path` config ("app/components"), this causes the i18n_scope for Posts::IndexPage to be the full file path like `Users.stephann.projects.myproject.app.pages.posts.index_page` instead `pages.posts.index_page`. 
- Other problem that I don't understand yet: the `render Posts::IndexPage.new(posts: posts)`  doesn't behave like a HTML response, this causes problem with Hotwire Turbo to not replace the current view with controller response, I found a solution using `respond_to` and make html format explicit, but I have to do this for every page render and pollutes the code:
```ruby
def index
  posts = Post.all
  
  respond_to do |format|
    format.html { render Posts::IndexPage.new(posts: posts) }
  end
end
```
### Motivation

With this feature, we can have some benefits from view_component applied to page templates:
-  A initializer with the needed information to render the page instead using the controller instance variables. This code
```ruby
# app/controllers/posts_controller.rb
before_action :set_post

def show
  load_extra_info
  @replies = ...
end

private

def set_post
  @post = ...
end

def load_extra_info
  ...
  @some_info = ...
end
```

Could become:
```
def show
  ...
  
  render Posts::ShowPage.new(post: post, replies: replies, some_info: some_info)
end
```

- It will help avoid Rails helpers (it can be bring some problems at larger scale), each page can be have their own methods:
Instead:
```
module PostsHelpers
  def render_replies
     ...
  end
  
  # some other many methods for other pages
end
```
We would have:
```
class Posts::ShowPage < ViewComponent::Base
  private
  
  def render_replies
    ...
  end
end
```

- In addition to helping to avoid Rails helpers, We will get a new layer to put some code that doesn't fit well in controllers or html, like setting up metatags, breadcrumbs and etc.

I know these problems can be solved in many other ways, but I think ViewComponent can be a great solution if it improves its use as a page template, going beyond just using it for small pieces.

Similar implementations:
- LuckyFramework: https://luckyframework.org/guides/frontend/rendering-html#creating-a-page
- Hanami: https://guides.hanamirb.org/v1.3/views/basic-usage/

**Comment by stephannv** [comment]
I'm pressed enter before complete the description. I will reopen soon

**Comment by boardfish** [comment]
Hi @stephannv! Sorry for the lack of activity here. I agree that components have the potential to replace what we'd otherwise call a presenter or view model. That's what we're considering past V3 - you can follow and support discussion in #618.

Both those bullet points you've got there would be good candidates for individual issues that we could potentially solve a lot sooner than #618, if you'd like to open those.

**Comment by stephannv** [comment]
Thanks @boardfish (sorry for late reply). I will wait for V3 to check if the issues I mentioned were solved and then open issues if not.

I'm closing this, but feel free to reopen.

**Comment by boardfish** [comment]
@stephannv #618's a greater-scope thing that'll probably take much more consideration – I haven't seen much movement on it in the last year, unless the core team are discussing this at GitHub. I do like the idea of it as a feature of, or extension to, ViewComponent. It's potentially worth discussing more, and I might have some thoughts to contribute to the issue to get that moving again.

> Other problem that I don't understand yet: the render Posts::IndexPage.new(posts: posts) doesn't behave like a HTML response, this causes problem with Hotwire Turbo to not replace the current view with controller response, I found a solution using respond_to and make html format explicit, but I have to do this for every page render and pollutes the code:

I think this issue *might* be in line with some of the Turbo/capture compatibility stuff, but I'm not confident of that – I'd recommend opening a PR to add a test case to cover this, and perhaps opening an issue if it's still a problem.

> The i18n doesn't work well because the i18n_scope/virtual_path uses view_component_path config ("app/components"), this causes the i18n_scope for Posts::IndexPage to be the full file path like Users.stephann.projects.myproject.app.pages.posts.index_page instead pages.posts.index_page.

I'm not sure if this has been fixed or not, so it'd be good to have the same as above.
