### ISSUE TITLE
Move ViewComponent to its own org

### ISSUE THREAD

**Issue by joelhawksley** [ViewComponent/view_component#1424]
I’d like to propose that we move ViewComponent to its own organization, `viewcomponent` for the following reasons:

1. So that ViewComponent’s identity can grow beyond the scope of just being a GitHub project. ViewComponent has > 165 contributors from across the industry, not just GitHub employees. 
2. So that we can formally extend ownership of the project to non-GitHub members of the community. This is currently not allowed under our organization policies.
3. Allow for other repos to be added to the project. For example, I’d be interested in moving VC::Form, Lookbook, demo repo and others into this proposed org.

What do y’all think?

**Comment by boardfish** [comment]
All for it! I suppose it does beg the question of whether the gem gets renamed to `viewcomponent` too, but I think that's something we'd need to do with a major release... It's worth thinking through the consequences for developers there.

Part of me wonders if there'd be a way to have Dependabot pick up on the rename. That'd give it a good signal boost.

**Comment by boardfish** [comment]
> I suppose it does beg the question of whether the gem gets renamed to viewcomponent too, but I think that's something we'd need to do with a major release...

Was this idea dropped, or is it still something we plan to do for v3?

**Comment by joelhawksley** [comment]
@boardfish I haven't given it any further thought. What do you think?

**Comment by boardfish** [comment]
I guess there are two sides to it – from the perspective of it not being the same as the org name, it's unintuitive. But from the perspective of it being the snake-case form of the constant name, much like `active_support`, for example, it is. There's also the fear that anyone using ViewComponent more passively might miss updates through Dependabot for a good while.

I feel like there might've been something else swaying me towards the idea at the time, but I think on the above basis, it seems sound to drop it.

**Comment by Spone** [comment]
I agree, let's stick with `view_component` 👍
