### ISSUE TITLE
Improve error message when using `renders_one :content`

### ISSUE THREAD

**Issue by danieldiekmeier** [ViewComponent/view_component#1498]
## Feature request

When naming a slot `content`, ViewComponent shows an argument error:

```rb
class MyComponent < ViewComponent::Base
  renders_one :content
end
```

```
ArgumentError: 
  AlertComponent declares a slot named content, which is a reserved word in the ViewComponent framework. 
  To fix this issue, choose a different name.
```

The argument validation happens here: https://github.com/github/view_component/blob/c5308ae62508925408625fffce3b420719093182/lib/view_component/slotable_v2.rb#L274-L280

I think this error message could be improved to tell the user that `content` already _is_ a slot, and they don't have to do anything.

### Motivation

While this error message is _correct_, I think it's not helpful enough. In our codebase, it lead to many developers creating a slot with another name, like `:text` or `:fill` or `:inside`, which has several problems:

- It' a worse name than `:content`
- It's completely unnecessary, if only we knew that `content` was an implicit slot that could always be used.

I think the ergonomics of this validation could be improved by explaining the special case of `content`.

### Suggestion

I could take a stab at solving this by introducing a special case for `:content`, which would say something like

```
ArgumentError:
  AlertComponent declares a slot named content, which is the name of the implicit slot. 
  To fix this issue, either use the implicit slot directly or choose a different name.
```

If this is acceptable for you, I'll gladly open a PR. 🥰

**Comment by Spone** [comment]
Thanks for opening an issue to discuss this! I'm all for improving error messages to be more helpful and actionable.

In this case, I'm not sure that using the phrase "implicit slot" make things clearer. I don't think we refer to `content` this way in the docs (but maybe I'm mistaken?)

Could you suggest another phrasing for the error message?

**Comment by danieldiekmeier** [comment]
@Spone You're right, that's a good point. In https://viewcomponent.org/guide/getting-started.html#implementation, I found this wording:

> Content passed to a ViewComponent as a block is captured and assigned to the `content` accessor.

My suggestion based on this would be something like:

```
ArgumentError:
  AlertComponent declares a slot named content, which is a reserved word in the ViewComponent framework.
  Content passed to a ViewComponent as a block is captured and assigned to the `content` accessor without having to create an explicit slot.
  To fix this issue, either use the `content` accessor directly or choose a different name.
```

But I'm afraid it's a little long. What do you think?

**Comment by Spone** [comment]
I agree it's a bit long, but it explains the issue pretty well, so I'd be up for this improvement.

If anyone want to suggest another (shorter) phrasing, please do!

**Comment by Spone** [comment]
I agree it's a bit long, but it explains the issue pretty well, so I'd be up for this improvement.

If anyone want to suggest another (shorter) phrasing, please do!

**Comment by joelhawksley** [comment]
I don't think it's too long at all ❤️ Open a PR?
