### ISSUE TITLE
Allow more flexibility in polymorphic slot names

### ISSUE THREAD

**Issue by TastyPi** [ViewComponent/view_component#1526]
## Feature request

It would be nice if there was more customisation in how polymorphic slots were named. Specifically I would like to have the polymorphic slot name be a suffix instead of a prefix, but I could also imagine use cases where the polymorphic slot name isn't included in the individual slot names at all.

Something like this for example:

```ruby
class MyFormComponent < ViewComponent::Base
  renders_many :fields, suffix: true, types: {
    text: TextFieldComponent,
    email: EmailFieldComponent,
    ...
  }
end
```

### Motivation

I'm creating a form component where naming slots like `text_field` would be more consistent with Rails instead of `field_text` that is currently forced.

**Comment by boardfish** [comment]
I've found a need for this myself and I'd be happy to work on this. I also wonder if having it this way around should be the default?

**Comment by joelhawksley** [comment]
Hmm. I'm not immediately convinced that it's worth introducing two potential naming schemes for polymorphic slots. My concern is that it could be quite confusing to have both approaches in a single application, or even across multiple applications.

I get that this would make certain slot names more idiomatic, but I don't feel like that's enough justification for the proposed end result.

I also worry about the pain of having to migrate to being a suffix if we decided to just change the behavior outright.

**Comment by boardfish** [comment]
I feel like this is important. In the example given above, the word order is important to understanding the function of the slot. `text_field` and `field_text` could mean two different things (a field for inputting text, or text contained within a field of unspecified type). This is bound to be the case for other uses of polymorphic slots. Where I've used the feature in the past, I've experienced friction related to this issue, so I'm supportive of the cause.

I don't feel as though the names of methods generated through polymorphic slots should be restrictive in the name of making it clear that the feature was used. If we think of polymorphic slots as a DSL around slots, I would argue it's more important for that DSL to help the developer make a coherent interface. 

I'd compare this case to the prefix and suffix features for enums in Rails. They're important in similar ways.

**Comment by TastyPi** [comment]
> If we think of polymorphic slots as a DSL around slots

It could even become a DSL:

```ruby
class MyFormComponent < ViewComponent::Base
  renders_one :field do |slot|
    slot.text_field TextFieldComponent
    slot.email_field EmailFieldComponent
    slot.select SelectComponent
  end
end
```

**Comment by joelhawksley** [comment]
@boardfish good point about enums. I'd be open to a PR that mimics' the Rails API.

**Comment by boardfish** [comment]
Great, I'll give it a shot!

**Comment by Spone** [comment]
To sum this up, if we were to mimic the [Rails API](https://api.rubyonrails.org/classes/ActiveRecord/Enum.html):

```rb
class Conversation < ActiveRecord::Base
  enum :status, [ :active, :archived ], suffix: true
  enum :comments_status, [ :active, :inactive ], prefix: :comments
end

# available methods:
conversation.active_status!
conversation.archived_status? # => false

conversation.comments_inactive!
conversation.comments_active? # => false
```

We would have:

```rb
class ListItemComponent < ViewComponent::Base
  renders_one :visual, prefix: true, types: {
    icon: IconComponent,
    avatar: AvatarComponent,
  }
  renders_one :field, suffix: true, types: {
    text: TextFieldComponent,
    email_field: EmailFieldComponent,
  }
end
```

so we could do:

```rb
render ListItemComponent.new do |c|
  c.with_avatar_visual # ... abridged for clarity
  c.with_icon_visual # ...
  c.with_field_field # ...
  c.with_email_field # ...
end
```

I guess the remaining question before working on the implementation is: Which form should be the default? It's currently the prefix, but in most cases I've been confronted to, the suffix version would have been clearer. If we change it, that would be a breaking change (but migrating is as easy as adding `prefix: true`)

**Comment by boardfish** [comment]
I agree that suffix should be the new default, since the first word of a polymorphic slot name generally tends to describe what's going in the slot, such as `text_field` in the example you gave there.

It'd be good to provide a generator/RuboCop rule to find uses of polymorphic slots without `prefix` or `suffix` specified and fill in the defaults to ease migration here.

**Comment by joelhawksley** [comment]
@boardfish @Spone perhaps it's time to write a PR? I'd be interested in seeing this in practice.

**Comment by Spone** [comment]
@joelhawksley definitely! I just wanted to sum up the state of the discussion before starting a PR.

@boardfish do you want to work on this or should I get started?

**Comment by camertron** [comment]
Before y'all start the implementation I'd like to propose a different API. The `prefix`/`suffix` options are fine, and I understand how they're consistent with enums, but aren't we just putting a bandage over the real problem? In my opinion, providing options around how the name is generated isn't going far enough. Moreover `prefix`/`suffix` are confusing. I feel like I'd have to go to the docs every time I used the feature to remind myself what they mean. Which part is the prefix/suffix?

Another potential issue is that `prefix: true` in @Spone's examples above is passed to `renders_one` even though it's specific to polymorphic slots.

I'd like to propose allowing the user to provide a custom method name, eg:

```ruby
class ListItemComponent < ViewComponent::Base
  renders_one :visual, types: {
    icon: { renderable: IconComponent, name: :icon_visual },
    avatar: { renderable: AvatarComponent, name: :avatar_visual },
  }
  renders_one :field, suffix: true, types: {
    text: { renderable: TextFieldComponent, name: :text_field },
    email_field: { renderable: EmailFieldComponent, name: :email_field },
  }
end
```

**Comment by Spone** [comment]
> Before y'all start the implementation I'd like to propose a different API.

Your thoughts are most welcome! That's why I wanted to reopen the discussion first :+1: 

> Moreover prefix/suffix are confusing. I feel like I'd have to go to the docs every time I used the feature to remind myself what they mean. Which part is the prefix/suffix?

I totally agree, I had to check the enum docs twice while writing my code sample.

> Another potential issue is that `prefix: true` in @Spone's examples above is passed to renders_one even though it's specific to polymorphic slots.

Yes, my mistake, it would only be for `renders_many`. But I guess someone could try with `renders_one` and be confused.

In your example, would the `name` be optional?

It feels a bit [WET](https://en.wikipedia.org/wiki/Don't_repeat_yourself#WET) to write `:visual`, `icon`, then `icon_visual` again.
Why do we need to keep the `icon` hash key then? Maybe I'm missing something, but can't we use the key to define the name?

```rb
class ListItemComponent < ViewComponent::Base
  renders_one :visual, types: {
    icon_visual: IconComponent,
    avatar_visual: AvatarComponent,
  }
  renders_one :field, types: {
    text_field: TextFieldComponent,
    email_field: EmailFieldComponent,
  }
end
```

As this is similar to the current syntax, we would probably need to support both the current and new syntax while we deprecate the former.

**Comment by camertron** [comment]
> Yes, my mistake, it would only be for `renders_many`. But I guess someone could try with `renders_one` and be confused.

Oh that's true, good point! I actually meant that the `prefix` and `suffix` options only make sense if you also pass `types`. I tried to address that by converting the `types` hash to a hash of hashes so it's clear how the options are related, eg. `icon: { renderable: IconComponent, name: :icon_visual }` instead of `icon: IconComponent`.

> In your example, would the name be optional?

That's a really good question. I think so, yes, since the duplication you mentioned doesn't feel great.

> Why do we need to keep the `icon` hash key then? Maybe I'm missing something, but can't we use the key to define the name?

That could work, although how would we disambiguate between 1) the lib choosing the name based on the hash key and 2) providing our own names as hash keys? What if `types` was an array instead, eg:

```ruby
class ListItemComponent < ViewComponent::Base
  renders_one :visual, types: [
    { renderable: IconComponent, name: :icon_visual },
    { renderable: AvatarComponent, name: :avatar_visual },
  ]
end
```

**Comment by camertron** [comment]
> EDIT: another approach could be to keep the existing syntax when defining slots, but changing the way we fill them

This is really interesting, but seems a little complicated. Let's keep brainstorming :)

**Comment by joelhawksley** [comment]
While I agree with @camertron's idea to have more flexibility, I wonder if it's necessary in practice.

I think the suffix true/false API is sufficient based on the cases provided.

**Comment by Spone** [comment]
Here is a draft PR: #1652
