### ISSUE TITLE
Unable to render content from slots in RSpec or Lookbook or direct preview files

### ISSUE THREAD

**Issue by danielnc** [ViewComponent/view_component#1537]
I have a very simple component that wraps part of my layout, when rending in views it works as expected, but I can't render slots in either lookbook or view_component preview
### Steps to reproduce
Component
```ruby
# frozen_string_literal: true

class Layout::Component < ApplicationViewComponent
  renders_one :header
  renders_one :main
end
```

Component.html
```erb
<%= render Primer::Box.new(classes: class_for(:box)) do %>
  <%= render Primer::Box.new(classes: class_for(:header_box)) do %>
    <% if header? %>
      <%= render(Primer::Beta::Heading.new(tag: :h2)) do %>
        <%= header %>
      <% end %>
    <% end %>
  <% end %>

  <%= render Primer::Box.new(classes: class_for(:main_box)) do %>
    <%= main %>
  <% end %>
<% end %>
```

View from the app that works
```erb
<%= render Layout::Component.new do |component| %>
  <% component.with_header do %>
    This is my header
  <% end %>

  <% component.with_main do %>
    This is my body
  <% end %>
<% end %>
```

This is the failing rspec
```ruby
  context "when rendering with header" do
    let(:component) do
      described_class.new do |c|
        c.with_header { "Header" }
        c.with_main { "Main" }
      end
    end

    it "renders", aggregate_failures: true do
      render_inline(component)

      is_expected.to have_css ".#{component.class_for(:box)}"
      is_expected.to have_css ".#{component.class_for(:header_box)}", text: "Header"
      is_expected.to have_css ".#{component.class_for(:main_box)}", text: "Main"
    end
  end
```

This is the preview that has both header and main sections empty, but the rest of the component is rendered as expected
```ruby
# frozen_string_literal: true

class Layout::Preview < ApplicationViewComponentPreview
  # @display resource_name "info_producer"
  def with_header
    render_component(Layout::Component.new) do |c|
      c.with_header do
        "Header"
      end
      c.with_main do
        "Body"
      end
    end
  end
end
```

### Expected behavior
My expected behavior is that for rspec and previews, both header and main sections would be rendered as it does for regular rails views when calling the component

### Actual behavior
slots are not rendered inside rspec or previews

### System configuration
**Rails version**:
Rails 7.0.4
**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]
**Gem version**:
2.72.0

**Comment by wooly** [comment]
I think we're experiencing this as well, but it's also happening when rendering `content` as well as slots.

**Comment by boardfish** [comment]
Hey folks! I thought I'd replied to this already, but apparently not... [This thread](https://github.com/ViewComponent/view_component/issues/1322#issuecomment-1172315202) may solve your issue.

**Comment by wooly** [comment]
Thanks @boardfish, I had worked my way to that solution too - calling `.to_s` on the content causes it to render correctly.

Thanks for the reply though!

**Comment by jacob-carlborg-apoex** [comment]
@danielnc your code in the spec is not exactly the same as the code in the application. In the application you're the passing block to the `render` method, which is correct. In the spec you're passing the block to the constructor of the component instead of to the block. Try passing it to the constructor and see if that helps.

**Comment by Spone** [comment]
@danielnc to clarify, here is the fix described by @jacob-carlborg-apoex 

```diff
  context "when rendering with header" do
    let(:component) do
-      described_class.new do |c|
-        c.with_header { "Header" }
-        c.with_main { "Main" }
-      end
+      described_class.new
    end

    it "renders", aggregate_failures: true do
-      render_inline(component)
+      render_inline(component) do |c|
+        c.with_header { "Header" }
+        c.with_main { "Main" }
+      end

      is_expected.to have_css ".#{component.class_for(:box)}"
      is_expected.to have_css ".#{component.class_for(:header_box)}", text: "Header"
      is_expected.to have_css ".#{component.class_for(:main_box)}", text: "Main"
    end
  end
```
