### ISSUE TITLE
Relative translations don't work in initializer

### ISSUE THREAD

**Issue by jcoyne** [ViewComponent/view_component#1577]
This is similar to #74

If I have an initializer and I use the translation helper, then I get the error:
```
Cannot use t(".link_text") shortcut because path is not available
```
This happens even after calling `super`

If I move the translation into an instance method, it works as expected.

Using view_component-2.75.0, rails-7.0.4, ruby 3.1.0

**Comment by joelhawksley** [comment]
@jcoyne thanks for filing this issue. Might you be up for writing a PR with a failing test? Perhaps @elia could have a look, then.

**Comment by elia** [comment]
This is expected, although I agree would be great to have them working in the initializer as well.

The reason it works as an instance method is that the method is most likely called after initialization and compilation of the component. Happy to review any proposal to make it work from the get go tho 🙌

**Comment by joelhawksley** [comment]
@jcoyne given @elia's response, are there any documentation changes you think we should make?

**Comment by jcoyne** [comment]
I suppose some warning in the documentation would be nice. I'm not at all clear why this timing concern exists. Maybe an explanation about that?

**Comment by joelhawksley** [comment]
@jcoyne perhaps we could just add a warning for now? Like this test case: https://github.com/ViewComponent/view_component/blob/c9b7d36e5dd2a043b20756cf5a6bdef3d3463902/test/sandbox/test/base_test.rb#L37. We could also add something to the docs.

**Comment by jcoyne** [comment]
@joelhawksley that would be really helpful

**Comment by joelhawksley** [comment]
@jcoyne cool. Would you be up for writing a PR? I can help clean up language if you get something started ❤️

**Comment by jcoyne** [comment]
No, because I don't understand the order problem were seeing. I don't understand what the compile step is or what that does.
