### ISSUE TITLE
render_preview is not respecting the default_preview_layout

### ISSUE THREAD

**Issue by xdmx** [ViewComponent/view_component#1599]
I've set `config.view_component.default_preview_layout = "component_preview"` in my `development.rb` and it's correctly been used when I open the previews (through Lookbook).

Now I'm starting to write tests on my components and I've discovered that there is the `render_preview` which allows to use the previews. But when I try to render any component it gets rendered with the `application`  layout instead of `component_preview`, which in my case causes errors as there are some methods there that are not available at the component level.

If I explicitly set the `layout 'component_preview'` in the component itself it works, but I think that given the global config it should work with that one as well.

**Comment by boardfish** [comment]
Your tests will be run with `Rails.env` set to `"test"`, so `config/environments/development.rb` won't be run and thus this setting won't take effect. You can move that setting into `config/application.rb`, and optionally limit the environments in which it'll take effect:

```rb
config.view_component.default_preview_layout = "component_preview" if Rails.env.in? %w[development production]
```
