### ISSUE TITLE
3.0.0 release candidate feedback

### ISSUE THREAD

**Issue by joelhawksley** [ViewComponent/view_component#1629]
👋🏻 Hi folks! We've shipped a release candidate for ViewComponent v3. Please provide feedback in this issue ❤️

**Comment by jcoyne** [comment]
I'm not seeing it https://rubygems.org/gems/view_component, did it get pushed?

**Comment by joelhawksley** [comment]
@jcoyne It's in progress. I wanted to have this issue open to mention in the changelog. 🐔, 🥚 , etc.

**Comment by jcoyne** [comment]
@joelhawksley got it. Thanks.

**Comment by tmaier** [comment]
I tried it. Looks good in general.

However, it would be great to have a solution for the forms-issue with this release... and if this means that the documentation just mentions the known and recommended work-arounds.

**Comment by camertron** [comment]
Hey @tmaier, thanks for the reminder re: #1432. A semi-recent [change](https://github.com/rails/rails/pull/45731) to action view may actually make our job easier with respect to supporting form helpers. I tried running our [action view compatibility tests](https://github.com/ViewComponent/view_component/blob/main/test/sandbox/test/action_view_compatibility_test.rb) on Rails main, but they all failed, so the Rails change alone isn't enough. I'll try having a look at this in more depth tomorrow. Regardless, I don't think form helper compatibility should block the v3 release.

**Comment by jacob-carlborg-apoex** [comment]
I found a minor issue that probably needs a breaking change to be fixed: https://github.com/ViewComponent/view_component/issues/1641. Would be nice to have a fix included in v3.

**Comment by tmaier** [comment]
The most simple approach on #1432 is to improve documentation. I opened a small Pull Request (#1644).

**Comment by barmintor** [comment]
I'm running a test against the RC, and I'm seeing a failure that would be explained by the collection counter param changing to a 0-indexed value rather than a 1-indexed value. Is that a documented change?

**Comment by barmintor** [comment]
LOL yes, it is a documented change. Thanks!

**Comment by jacob-carlborg-apoex** [comment]
The changelog says:

> Remove deprecated `rendered_component` in favor of `rendered_content`

But `rendered_content` is marked as `@private` and the deprecation message says to use `page` instead of `rendered_component` (although they're no exactly the same).

**Comment by Spone** [comment]
Happy to report that [tests pass on view_component-form](https://github.com/pantographe/view_component-form/pull/136), when running view_component `v3.0.0.rc1`!

**Comment by jdelStrother** [comment]
Would v3 be a good point to discuss #1528 again to avoid Rails initialization-order problems?

**Comment by leighhalliday** [comment]
We've been on 3.0 release candidate versions at Wrapbook for over a month now and so far no issues to report! Our biggest challenge to get from 2.0 to 3.0 was to switch to `with_` prefix for all the slot calls.

We did this by going component by component, converting and then changing it to raise exceptions in tests if the old style was used (via looking at the deprecation warning)... till we could eventually at that check at the `ApplicationComponent` level... then upgrade was easy at that point!
