### ISSUE TITLE
Conflict with private API in TestHelpers

### ISSUE THREAD

**Issue by jacob-carlborg-apoex** [ViewComponent/view_component#1641]
### Steps to reproduce

I have this RSpec test:

```ruby
RSpec.describe FooComponent do
  def controller
    FooController
  end
  
  class FooController < ::ApplicationController
    def action_name
      "index"
    end
  end

  it "renders a Tailwind page" do
    with_controller_class(controller) do
      render_inline(FooComponent.new)
      expect(page).to have_content("foo")
    end
  end
end
```

### Expected behavior
I expect the test to pass.

### Actual behavior
Running this test results in the following unexpected error:

```
NoMethodError:
 undefined method `view_context' for FooController:Class
 Did you mean?  view_context_class
# /Users/jacobcarlborg/.rvm/gems/ruby-2.7.2@auti/gems/view_component-2.82.0/lib/view_component/test_helpers.rb:57:in `render_inline'
```

The problem is that `TestHelpers` contains some private API:

https://github.com/ViewComponent/view_component/blob/9c5a9c7727b6186ece8b86fb832e7f6fd969580a/lib/view_component/test_helpers.rb#L112

And since `TestHelpers` is included in the test context, the private API is now suddenly available to tests. I unknowingly created a method, `controller`, that overwrote one of the methods part of the private API thereby breaking `TestHelpers`.

This is probably not avoidable with they way `include` works in Ruby. But perhaps the risk of causing a conflict can be reduced by prefixing all symbols (methods, instance variables, constants, etc.) with an underscore or something similar. Since this would technically be breaking change it would be nice if some form of solution could be included in ViewComponent 3.

### System configuration
**Rails version**: 6.1.5.1
**Ruby version**: 2.7.2
**Gem version**: 2.82.0

**Comment by joelhawksley** [comment]
@jacob-carlborg-apoex thanks for filing this bug. As `controller` is a private method, I don't think this would be a breaking change. That being said, we should fix it! Can you open this failing case as a PR? Feel free to suggest a fix if you'd like, or I'd be happy to take a look.

**Comment by jacob-carlborg-apoex** [comment]
Sure, I'll try and do that.

**Comment by jacob-carlborg-apoex** [comment]
@joelhawksley I'm working on fix for this issue. But I've found several tests that uses these methods that are private API. Should I fix the tests or should we think about making these methods public?

**Comment by joelhawksley** [comment]
@jacob-carlborg-apoex let's fix the tests for now and discuss on the PR ❤️

**Comment by jacob-carlborg-apoex** [comment]
@joelhawksley I've created a PR: https://github.com/ViewComponent/view_component/pull/1646.

**Comment by jacob-carlborg-apoex** [comment]
Thanks.
