### ISSUE TITLE
duplicate elements when combining helpers and <%=

### ISSUE THREAD

**Issue by dbil25** [ViewComponent/view_component#1651]
### Steps to reproduce
this component:
```erb
<div>
  <%= helpers.tag.div do %>
    content of helper and =
  <% end %>

  <% helpers.tag.div do %>
    content of helper and no =
  <% end %>

  <% tag.div do %>
    content of no helper and no =
  <% end %>

  <%= tag.div do %>
    content of no helper and =
  <% end %>
</div>
```

### Expected behavior
```html
<div>
  <div>
    content of helper and =
  </div>

  <div>
    content of no helper and =
  </div>
</div>
```

### Actual behavior
```html
<div>
  content of helper and =
  <div>
    content of helper and =
  </div>
  content of helper and no =
  <div>
    content of no helper and =
  </div>
</div>
```
its as if when we are using the `helpers` keyword, it gets rendered even if we use `<%` instead of `<%=`. And when we do user `<%=`, then it renders it in double.

i'm 99% sure its the root cause of issue https://github.com/ViewComponent/view_component/issues/1099 and https://github.com/viewcomponent/view_component/issues/241, and might be related to some other issues like https://github.com/viewcomponent/view_component/issues/241

### System configuration
**Rails version**:
Rails 7.0.3.1
**Ruby version**:
ruby 3.1.2p20
**Gem version**:
2.62.0

**Comment by Spone** [comment]
Hi @dbil25 this is about to be fixed by https://github.com/ViewComponent/view_component/pull/1650 :)
