### ISSUE TITLE
ViewComponentsSystemTestController can render any file

### ISSUE THREAD

**Issue by nickmalcolm** [ViewComponent/view_component#1663]
`ViewComponentsSystemTestController` renders whatever file exists at a user-controlled path. This could lead to an Arbitrary File Read vulnerability.

MR that introduced the controller: https://github.com/ViewComponent/view_component/commit/5769fe26b71dc39416a20ec484bb9e4b52c0c94f

It'd be unlikely for anyone to currently use this in a vulnerable way. This issue would be a defense-in-depth best practice to prevent people from accidentally misusing the Controller, or mitigate an error introduced to this gem later down the line.

I've created an issue instead of a PR as there are a few ways you could remediate this:

- Detect and raise an error if `params.permit(:file)[:file]` resolves to a file outside of `/tmp/view_components`, and/or
- Raise an error if the method is called in a non-test environment, and/or
- Add documentation to the Controller with a big warning

### Steps to reproduce

1. Set up an example `view_component` app following https://viewcomponent.org/CONTRIBUTING.html#creating-a-rails-application-to-demonstrate-a-viewcomponent-bug
2. Add `get "_system_test_entrypoint", to: "view_components_system_test#system_test_entrypoint"` to `routes.rb`
3. Navigate to `http://localhost:3000/_system_test_entrypoint?file=../../config/master.key` (or similar)

![Screenshot 2023-02-20 at 12 58 00 PM](https://user-images.githubusercontent.com/342417/219983345-ca8f0782-e9b2-465d-87cd-62052333e9d8.png)

### Expected behavior

`ViewComponentsSystemTestController` should refuse to render anything outside `./tmp/view_components` OR rails an error `unless Rails.env.test?`

### Actual behavior

`ViewComponentsSystemTestController` renders a sensitive file. It depends on the permissions the Rails server process has - one easy file to read is `master.key` or other config files. If Rails has permission it could be used to read sensitive system files at the root directory.

### System configuration
**Rails version**: Rails 6.1.7.2

**Ruby version**: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [arm64-darwin22]

**Gem version**: 2.82.0

### References

- CWE-22: Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal') https://cwe.mitre.org/data/definitions/22.html
- CWE-23: Relative Path Traversal https://cwe.mitre.org/data/definitions/23.html
- https://portswigger.net/web-security/file-path-traversal

**Comment by joelhawksley** [comment]
@nickmalcolm thank you for filing this report! 

As of now, the route to this controller is only mounted in the test environment: https://github.com/ViewComponent/view_component/blob/main/lib/view_component/engine.rb#L141, so a consumer would have to mount this route themselves as you've suggested, which I think is pretty unlikely.

However, I think your caution here is appropriate and that we should take _all_ of your suggested remediation steps, at least in some form. Would you be up for getting a PR started? I'd be happy to pair on it with you (email me: joelhawksley@github.com) or take this on myself.
