### ISSUE TITLE
Duplicated block content when using the helpers - proxy

### ISSUE THREAD

**Issue by kulturbande** [ViewComponent/view_component#1727]
When you use the `helpers` proxy in combination with a block - helper, the captured content of the block is duplicated.

### Steps to reproduce
1. Create a view component
2. Test following ERB template:
```erb
<%= helpers.content_tag(:div) do -%>
  Test
<% end %>
```
3. The result is a duplicated content. Result:
```html
Test <div>Test</div>
```

### Expected behavior
The content is not duplicated. Without the proxy the result is as expected.

Template:
```erb
<%= content_tag(:div) do -%>
  Test
<% end %>
```
Result:
```html
<div>Test</div>
```
### Actual behavior
As mentioned in the list to reproduce the output generates duplicate content.

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.2.2

**Gem version**: 3.0.0

**Comment by Spone** [comment]
Hi! Please try the `capture_compatibility_patch_enabled` option, see https://viewcomponent.org/api.html#capture_compatibility_patch_enabled

**Comment by kulturbande** [comment]
Thx for the fast response. If `capture_compatibility_patch_enabled`is enabled these behavior is gone. Should I close the issue?

**Comment by kulturbande** [comment]
Thx for your help
