### ISSUE TITLE
Allow slot to render other slots

### ISSUE THREAD

**Issue by inkstak** [ViewComponent/view_component#1784]
## Feature request

I've implemented the following components :

```ruby
class CardComponent < ViewComponent::Base
  renders_one :action, ::ButtonComponent
end

class TemplateComponent < ViewComponent::Base
  renders_one :action, ::ButtonComponent
end
```

I would like to be able to forward the action from one component to another:

```erb
# template_component.html.erb

<%= render CardComponent.new do |card| %>
  <% card.with_action(action) if action? %>
<% end %>
```

Then, I'll use the same API whenever I use one component or the other :

```erb
<%= render TemplateComponent.new do |card| %>
  <% card.with_action("Click here", href:, icon:, data:) %>
<% end %>

<%= render CardComponent.new do |card| %>
  <% card.with_action("Click here", href:, icon:, data:) %>
<% end %>
```

### Motivation

We have implemented many "low-level" components for many UI features and we are now implementing "high-level" components that rely on these small components.

We would like to standardize many recurring slots between all these components, using the same API.

### Current workaround

Our current implementation is pretty simple and works as soon as our slots are defined using a class or a string.

If the input of the slot is already a `ViewComponent::Slot` we just call `:to_s`. Otherwise, we build the slot instance.

```ruby
class ApplicationViewComponent < ViewComponent::Base
  def self.renders_one(slot_name, callable = nil)
    super(slot_name, override_slot_callabble_to_accept_other_slots(callable))
  end

  def self.renders_many(slot_name, callable = nil)
    super(slot_name, override_slot_callabble_to_accept_other_slots(callable))
  end

  def self.override_slot_callabble_to_accept_other_slots(callable)
    return callable unless callable.is_a?(Class) || callable.is_a?(String)

    lambda { |*args, **options|
      if args.first.is_a?(ViewComponent::Slot)
        args.first.to_s
      elsif callable.is_a?(Class)
        callable.new(*args, **options)
      elsif callable.is_a?(String)
        self.class.const_get(callable).new(*args, **options)
      end
    }
  end

  private_class_method :override_slot_callabble_to_accept_other_slots
end
```

### Improvements

I'm currently looking to improve this workaround to override default options when forwarding the slot to another component :
Somehing like :

```erb
# template_component.html.erb

<%= render CardComponent.new do |card| %>
  <% card.with_action(action, class: "primary") if action? %>
<% end %>
```

**Comment by boardfish** [comment]
Hey @inkstak, thanks for raising this with us! 👋 

So what I'm seeing here is that you'd like to allow some parent component to be able to set a slot on its child component. The way I've done this in the past is, in the case of your example there, to define a method on TemplateComponent like this:

```rb
class CardComponent < ViewComponent::Base
  renders_one :action, ::ButtonComponent
end

class TemplateComponent < ViewComponent::Base
  renders_one :action, ::ButtonComponent
  renders_one :card, ::CardComponent

  def with_action(*args, &block)
    with_card { |card| card.with_action(*args, &block) }
  end
end
```

`TemplateComponent`'s template should call:

```html.erb
<%= card || render(CardComponent.new) %>
```

Then the view can go about things a few different ways as appropriate:

```html.erb
<h1>Card is unset – fallback to default card (component template)</h1>
<%= render TemplateComponent.new %>
<h1>Method shortcut to get to the card's action (defined on component class)</h1>
<%= render TemplateComponent.new do |c| %>
  <% c.with_action("Doing things!") %>
<% end %>
<h1>Overriding args on the card and setting the action (standard use of slots)</h1>
<%= render TemplateComponent.new do |c| %>
  <% c.with_card(some_arg: true) { |card| card.with_action("Doing things!") } %>
<% end %>
```

If you want to _dynamically_ delegate to some child component, so forward _all_ slot usage to the child component...that's theoretically possible, and I almost wonder if we should provide a DSL method for it 🤔 Worth a discussion, really! But I hope this solution does what you're asking – let me know if you've got any more questions.

**Comment by inkstak** [comment]
Thanks for the suggestion.
I've tried it but it won't work with several slots to forward :

```ruby
class Modal::Component < ApplicationViewComponent
  renders_one :header
  renders_one :body
  renders_many :actions
end

class Card::Component < ApplicationViewComponent
  renders_one :header
  renders_one :body
  renders_many :actions
end

class Template::Component < ApplicationViewComponent
  renders_one :header
  renders_one :body
  renders_many :actions
end
```

```erb
<%# template_status/component.html.erb %>

<% if request.variant == :modal %>
  <%= render Modal::Component.new do |modal| %>
    <% modal.with_header(header) if header? %>
    <% modal.with_body(body || content) %>
    <% modal.with_actions(actions) if actions? %>
  <% end %>
<% else %>
  <%= header %>
  <%= render Modal::Component.new do |card| %>
    <% card.with_body(body || content) %>
    <% card.with_actions(actions) if actions? %>
  <% end %>
<% end %>
```

**Comment by boardfish** [comment]
Ah, this is interesting. In this case we're forwarding passthrough slots – I can't say I've tried this before, but perhaps you'll need to use the block form instead of passing your content to `with_` directly:

```html.erb
<%# template_status/component.html.erb %>

<% if request.variant == :modal %>
  <%= render Modal::Component.new do |modal| %>
    <% modal.with_header do %><%= header %><% end %>
    <% modal.with_body do %><%= body || content %><% end %>
    <% modal.with_actions do %><%= actions %><% end %>
  <% end %>
<% else %>
  <%= header %>
  <%= render Card::Component.new do |card| %>
    <% card.with_body do %><%= body || content %><% end %>
    <% card.with_actions do %><%= actions %><% end %>
  <% end %>
<% end %>
```

That's without the conditionals in your example, but see if it works out.

**Comment by boardfish** [comment]
It's probably still possible by passing things straight to `with_`, but maybe there's something you'd need to do with `capture` or calling `to_s` on it.

**Comment by inkstak** [comment]
Thanks for the suggestions.

It'll work for simple slots, those rendered without wrapping markup : 

```ruby
renders_one :body
renders_one :header, ->(label) { label || content }
```

But as soon as you introduce markup, some part will be duplicated.

```ruby
class Button::Component < ApplicationViewComponent
  def initialize(**html_options)
    @html_options = html_options
  end 

  def call
    content_tag :button, content, **@html_options
  end
end

class Modal::Component < ApplicationViewComponent
  renders_many :actions, ::Button::Component
end

class Template::Component < ApplicationViewComponent
  renders_many :actions, ::Button::Component
end
```

```erb
<%= render Template::Component.new do |template| %>
  <% template.with_action(class: "primary") do %>
    Click here
  <% end %>
<% end %>

# => <button><button class="primary">Click here</button></button>
```

The only another approach to avoid overriding `renders_one`/`renders_many` I throught is to have a special slot to render raw content :

```ruby
class Modal::Component < ApplicationViewComponent
  renders_many :actions, ::Button::Component
  renders_one :raw_actions
end

class Template::Component < ApplicationViewComponent
  renders_many :actions, ::Button::Component
end
```

```erb
<%# modal/component.html.erb %>

<% if actions? || raw_actions? %>
<div class="modal__actions">
  <%= actions %>
  <%= raw_actions %>
</div>
<% end %>

<%# template/component.html.erb %>

<%= render Modal::Component.new do |modal| %>
  <% if actions? %>
    <% modal.with_raw_actions do %>
      <% actions.each do |action| %>
        <%= action %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
```

It works but I'm not a big fan.

**Comment by reeganviljoen** [comment]
@inkstak would you be able to write any failing tests so we can get an idea of how you would like this feature to look, so we can possibly start development

**Comment by camertron** [comment]
Hey @inkstak, this is a really interesting question and something I've thought a lot about while developing [`NavList`](https://primer.style/design/components/nav-list/rails/alpha) and [`ActionMenu`](https://primer.style/design/components/action-menu/rails/alpha). I initially wanted to use composition instead of inheritance, but eventually came to the conclusion inheritance worked better for those specific use-cases. However, composition is still an important pattern to consider. In experimenting with both, I wrote up an implementation for delegating slots that feels similar to ActiveSupport's [`Module.delegate`](https://www.rubydoc.info/gems/activesupport/Module:delegate):

```ruby
class ParentComponent < ViewComponent::Base
  renders_one :header
  renders_many :items
end

class ChildComponent < ViewComponent::Base
  include ViewComponent::DelegatedSlots

  delegate_renders_one :header, to: :@parent
  delegate_renders_many :items, to: :@parent

  def initialize
    @parent = ParentComponent.new
  end
end
```

My proposal also included being able to modify the arguments that would eventually be passed to the actual slot in `ParentComponent`, but it was pretty messy.

Another possible solution I've noodled around with is providing an API method for defining slot-like methods that aren't actually slots, eg:

```ruby
class ParentComponent < ViewComponent::Base
  renders_one: header
end

class ChildComponent < ViewComponent::Base
  # this defines a method named `#with_header`, but it isn't actually a slot
  define_renders_one_slot_setter(:header) do |...|
    @parent.with_header(...)
  end

  def initialize
    @parent = ParentComponent.new
  end
end
```

Right now the best way to do this is the way @Spone mentioned, i.e. by defining methods like `#with_action` that forward the arguments to a composed component instance. We do that in quite a few places in primer/view_components and it works well.

> I've tried it but it won't work with several slots to forward

Can you elaborate? It wasn't clear to me in the example you provided why the method approach doesn't work for several slots.

**Comment by inkstak** [comment]
Hi @camertron, thanks for your feeedback.

> I've tried it but it won't work with several slots to forward

It was a response to the [solution](https://github.com/ViewComponent/view_component/issues/1784#issuecomment-1607052530) proposed by @boardfish.  
In the example below, both slots `header` and `body` have to be forwarded to the same `card` component.  
However, each call to `with_card` initialize a new CardComponent and dont use the same `card`.

```ruby
class CardComponent < ViewComponent::Base
  renders_one :header
  renders_one :body
end

class TemplateComponent < ViewComponent::Base
  renders_one :card

  def with_header(*args, &block)
    with_card { |card| card.with_header(*args, &block) }
  end

  def with_body(*args, &block)
    with_card { |card| card.with_body(*args, &block) }
  end
end
```

**Comment by inkstak** [comment]
@reeganviljoen Here is a  failing test : https://github.com/inkstak/view_component/commit/e3829a7b444100624314cbe7e108e4628ff422a2

I'll try to find a solution on my side

**Comment by camertron** [comment]
@inkstak right, that's why @Spone and I are suggesting using plain 'ol Ruby methods instead of slots. Have you found a workaround or would it be beneficial to continue the conversation?

**Comment by Spone** [comment]
Hey @camertron, I think you're confusing me with @boardfish in this thread ☺️

**Comment by inkstak** [comment]
Hi ! Since all workarounds add some complexity, we've moved to a more classic but simpler approach on templates components.

**Comment by camertron** [comment]
@Spone woops, you're right, my bad!

@inkstak ok great, I'll close this issue then 😄
