### ISSUE TITLE
`ViewComponent::Base#with_<slot_name>` should return `self`

### ISSUE THREAD

**Issue by boardfish** [ViewComponent/view_component#1785]
This came up in discussion with @fuzzylogicxx just now. It's sort of adjacent to https://github.com/ViewComponent/view_component/discussions/1647.

When setting a slot on a component rendered inside a lambda, it's necessary to return that component, otherwise the slot inside the component will be rendered instead.

### Using the return value of `#with_icon`

```rb
class DropdownComponent < ApplicationComponent
  renders_one :button, -> { ButtonComponent.new.with_icon("test") }
end
```

```html
<div id="dropdown">
  <div id="icon">test</div>
</div>
```

### Using the `ButtonComponent` instance

```rb
class DropdownComponent < ApplicationComponent
  renders_one :button, -> { ButtonComponent.new.tap { _1.with_icon("test") } }
end
```

```html
<div id="dropdown">
  <div id="button">
    <div id="icon">test</div>
  </div>
</div>
```

Not returning the manipulated `ButtonComponent` means you end up skipping a step and returning the `IconComponent`.

Nothing's jumping out at me as to why `with_<slot_name>` returns the slot component rather than the parent component. I think in order to enable things like this, and perhaps also to help tests involving slots to read better, `with_<slot_name>` should return `self`.

**Comment by camertron** [comment]
Hey @boardfish, I think returning the slot instance enables things like

```ruby
ButtonComponent.new.with_icon("test").with_content("abc")
```

Really, you can call any `Slot` method or any method on the wrapped component object (since `Slot` delegates to the component). I'm pretty sure I've seen this pattern used in the GitHub codebase, so I assume other companies are doing it too. Changing `#with_*` methods to return `self` could potentially break a bunch of code.

**Comment by reeganviljoen** [comment]
@camertron could we add this pattern to the docs as a way to get the component with slots

**Comment by camertron** [comment]
@reeganviljoen hmm I'm not sure what you mean? We do mention this in the docs [here](https://viewcomponent.org/guide/slots.html#with_content), is that what you were looking for?
