### ISSUE TITLE
Render Collection with Variant

### ISSUE THREAD

**Issue by CoderMiguel** [ViewComponent/view_component#1788]
I have recently discovered that ViewComponents will accept ActionPack variants, but ran into some issues when trying to get this behavior to work in conjunction with the `with_collection` method.

The following sudo-code seems to only return the rendering of the default template, instead of the variant rendering:
```ruby
render MyComponent.with_collection(MyModel.scope), variant: :option
```
after finding this [issue](https://github.com/ViewComponent/view_component/issues/319) and the follow up [PR](https://github.com/ViewComponent/view_component/pull/429), i was expecting to be able to do this:

```ruby
MyComponent.with_collection(MyModel.scope).with_variant(:option)
```

but the `with_variant` method doesn't seem to exist as described in the PR.  I was only able to find reference to `with_variant` method here:
https://github.com/ViewComponent/view_component/blob/a35641ef4f82a8fd10e4669c8afef901e5bcadce/lib/view_component/test_helpers.rb#L122

Note: It appears that some of the functionality introduced by that PR is still present, but there may have been a move away from that method that I have missed.  Which has lead me to make my own method:

I here is a sudo-code of my method, without some of the customizations in the method that I am actually using:
```ruby
def render_collection_in(view_context:, collection:, variant: nil)
  with_collection(collection).then do |collection_component|
      # I duplicated the view_context here as to not persist the variant manipulation outside the scope of this method's use.
      view_context.dup.then do | dup_view_context|
        dup_view_context.lookup_context.variants = Array.wrap(variant) unless variant.blank?

        collection_component.render_in(dup_view_context)
    end
  end
end
```

### Motivation

I feel like this functionality would be helpful to be an integrated part of ViewComponents.  Especially if it supported the `render` method and it's variant option and did not force the use of `render_in` and passing in the view_context unless explicitly desired.

```ruby
render MyComponent.with_collection(MyModel.scope), variant: :option
# or 
render MyComponent.with_collection(MyModel.scope, variant: :option)
```

**Comment by boardfish** [comment]
Hey @CoderMiguel, thanks for raising this issue! Variants were deprecated a while back, and I believe `with_variant` itself was removed, if memory serves. The preferred pattern in ViewComponent is to have separate components, as opposed to what `with_variant` enabled, which was for a single component to have multiple possible template.

I'd recommend switching on the request variant (or whatever you're using) before choosing the component to render. What you may want to do, depending on how widely you're doing this, is have a factory method or a case statement. Either something akin to this at the controller level, if you're just doing it once or twice:

```rb
def component_to_render(variant = request.variant)
  if variant == :mobile
    SomeComponent
  else
    SomeOtherComponent
  end
end
```

...or something like this, if it's more widespread:

```rb
module SomeComponent
  def self.with_variant(variant)
     # ... similar conditional to above
  end
end
```

And if you're going for what `with_variant` was doing before, you'll benefit from using `include`ing modules to share code across components where necessary.

**Comment by CoderMiguel** [comment]
I will refactor this to different ViewComponents, I will need to ensure that I can still get the different views from the same logic.  I can probably use the [`render_parent`](https://viewcomponent.org/guide/templates.html#rendering-parent-templates) and [inherited](https://viewcomponent.org/guide/templates.html#inherited) approaches for fallback behavior that would be similar to the variant behavior described in the documentation.

>With this set of variants Rails will look for the following set of templates and use the first that exists.
>app/views/home/index.html+mobile.erb
>app/views/home/index.html+desktop.erb
>app/views/home/index.html.erb

Just wanting to get on the same page:

When you say Variants were deprecated, in what context are they deprecated? Because they seem to be alive and well in [Rails](https://guides.rubyonrails.org/layouts_and_rendering.html#the-variants-option) and the ViewComponent [documentation](https://viewcomponent.org/guide/templates.html#templates) 
and the actual code that was sudo-coded in the initial description is working in Rails 7.

Regardless, that would make sense that the `with_variant` went away with that change.

**Comment by boardfish** [comment]
Those things sound like a good way forward! I'm not seeing anything related to variants at least besides the testing documentation – it's worth us checking if this is still necessary. I'm strictly talking about the `with_variant` method within ViewComponent, rather than the request variant feature of Rails.

**Comment by CoderMiguel** [comment]
Awesome, thanks for the feedback.

**Comment by reeganviljoen** [comment]
@boardfish even tho gh variants are deprecated they still exist in the code base, could we possibly love OK at completely removing it
