### ISSUE TITLE
Fields_for causes some kind of weird loop with Reform & Slim

### ISSUE THREAD

**Issue by ajdubovoy** [ViewComponent/view_component#1822]
### Steps to reproduce

I have this code, where `@form` is an instance of a Reform form object:

```slim
= simple_form_for @form do |f|
  = f.simple_fields_for :tiles do |tile_form|
    = tile_form.collection_radio_buttons :tile_style_id, TileStyle.all, :id, :name
```

This works absolutely fine in a Rails view. But if I parse it out into a ViewComponent and render like:

```slim
= render Floorplans::FormComponent(form: @form)
```

Then I get a really crazy behavior.

### Expected behavior
I'd expect that when copying the code into a component and rendering the component with the only required argument, it should work fine.

### Actual behavior
It does render, but it creates a mise-en-abime effect. The resulting HTML is something like this:

```
form
  tile fields
    tile fields
      tile fields
         tile fields
```

It keeps on rendering the tile fields over and over again, inside of each other. I should mention too that even if my component HTML is like:

```slim
= simple_form_for @form do |f|
  = f.simple_fields_for :tiles do |tile_form|
    div TEST
```

Then it will render hundreds of divs that say TEST, which makes no sense since there are only 25 tile in my db (and it would only render 25 times if I copied this into a normal Rails view). And, after maybe 10 divs, it will start somewhat randomly putting the divs inside of each other. And then it will start rendering _other_ parts of the component inside of those divs, which makes even less sense to me. It seems like it's almost looping re-rendering of the enter component but before it closes all the elements.

My conclusion was to not use ViewComponent for this form but I wish I could have.

**Backtrace**:

### System configuration
**Rails version**:
7.0.4.2

**Ruby version**:
3.1.2

**Gem version**:
3.5.0

**Comment by Spone** [comment]
Hi! Please try enabling the [capture_compatibility_patch_enabled](https://viewcomponent.org/api.html#configuration) option, it should fix this issue.

**Comment by reeganviljoen** [comment]
@adrianthedev amy updates on this issue?

**Comment by camertron** [comment]
Hey @ajdubovoy, sounds like this is no longer an issue for you. If you're still running into this, feel free to re-open 😄

**Comment by ajdubovoy** [comment]
Sorry for my delay. That worked like a charm. Thank you!
