### ISSUE TITLE
Capture compatibility patch isn't documented at Known Issues page

### ISSUE THREAD

**Issue by boardfish** [ViewComponent/view_component#1838]
https://viewcomponent.org/known_issues.html doesn't mention enabling the capture compatibility patch as a solution to the first two issues. I'm unsure as to why, but it'd be good to add it.

I also think it'd be good to have some explanation there as to why the patch is something that needs to be enabled. (My memory of how it works is hazy, but I assume it's patching Action View.)

**Comment by camertron** [comment]
Agreed! @boardfish do you have a few minutes to take this on?
