### ISSUE TITLE
Replace helpers with explicit api in v4

### ISSUE THREAD

**Issue by reeganviljoen** [ViewComponent/view_component#1848]
Thanks for the good discussion above y'all, I generally agree that we should keep it `helpers` to stay closer to Rails naming and conventions, but I think this spurred some great conversation. I love the idea of adding a "did you mean" too!

Personally, for V4 I'd want us to consider _removing_ `helpers` as-is and try to prevent folks from `include`ing helpers onto components in favor of a more explicit API like:

```ruby
class MyComponent < ViewComponent::Base
  use_helper :current_user
end
```

The thought being that it's much more explicit about where your data dependencies are coming from, and mocking them in unit tests is significantly easier. I don't have any plans to push that forward at the moment, but just something I've been thinking on.

_Originally posted by @BlakeWilliams in https://github.com/ViewComponent/view_component/issues/1836#issuecomment-1702774344_

**Comment by reeganviljoen** [comment]
@boardfish @BlakeWilliams @Spone @camertron I closed the previous helpers issue and created this issue to discuss @BlakeWilliams suggestion

**Comment by reeganviljoen** [comment]
@BlakeWilliams since you gave us the comment on this I was thinking maybe you can give us a bit of an explanation, your thoughts, some concerns, benefits, etc about this possible change

**Comment by camertron** [comment]
@reeganviljoen we discussed this internally and I think we're on board to give this new API a try. What we have done in the past for changes like this is to define a module that consumers can opt-into using, eg:

```ruby
class MyComponent < ViewComponent::Base
  include ViewComponent::HelpersApi

  use_helper :current_user
end
```

It would also be nice to come up with an API that allows these helper methods to be stubbed/mocked in the test environment. Any ideas there? We came up with this, but maybe there's a better option:

```ruby
class Test < Minitest::Test
  def test_something
    with_helpers(:current_user, -> { User.new }) do
      render_inline(...)
    end
  end
end
```

Or maybe:

```ruby
class Test < Minitest::Test
  def test_something
    renderer = TestRenderer.new
    renderer.with_helper(:current_user) do
      User.new
    end
    renderer.render(TestComponent.new(...))
  end
end
```

Thoughts?

**Comment by reeganviljoen** [comment]
@camertron I agree with the above with a single addition, maybe adding a deprecation warning in when helpers is used similar to what happened with `require: engine` in v3

**Comment by camertron** [comment]
@reeganviljoen yeah, we would definitely add a deprecation warning if/when we think the feature has had long enough to mature.

**Comment by reeganviljoen** [comment]
@camertron I will be working towards a working example this weekend, then.
