### ISSUE TITLE
Conflit using Dry Monads and View Component

### ISSUE THREAD

**Issue by devaniljr** [ViewComponent/view_component#1851]
I'm having a problem while using ViewComponent with Dry Monads. Here my code:

```ruby
require "dry/monads"

class Dashboard::Course::Marketing::StatsComponent < ViewComponent::Base
  include Dry::Monads[:result, :do]

  def initialize(course:)
    @course = course
  end
end
```

But this give me the error:

```txt
NoMethodError in Dashboard::Course::Marketing::Marketing#index

super: no superclass method `call' for
#<Dashboard::Course::Marketing::StatsComponent:0x00007fa01f1c5d38
```

If I remove the `require "dry/monads"`, the code starts working again. What could be causing this issue? Could there be an issue with how I'm importing Dry Monads? Dry Monads works well in the all other classes in the repo.

**Comment by devaniljr** [comment]
I found a way to work around the issue as follows:

```ruby
require "dry/monads/do"
include Dry::Monads::Do.for(:fetch_video_and_signature) # a specif method where I'm using the gem
```

I tried to be as specific as possible and included it within a method where the Dry Monads gem was being used. However, I'm still uncertain about the root cause of the problem.

**Comment by camertron** [comment]
Hey @devaniljr, this is an interesting one. It looks like dry-monads defines a `#call` method, which `ViewComponent::Base` isn't expecting. Can you play around in `irb` to see what's defining the `#call` method?

```ruby
Dashboard::Course::Marketing::StatsComponent.method(:call).source_location
```

**Comment by camertron** [comment]
I'm going to close this for now, as there hasn't been any activity in more than a month. @devaniljr, please feel free to re-open if you'd like to continue the conversation.
