### ISSUE TITLE
`with_request_url` test helper does not work with `request.fullpath`

### ISSUE THREAD

**Issue by robbevp** [ViewComponent/view_component#1867]
When components use `request.fullpath` instead of `request.path` the same test using `with_request_url` will fail for one, but not for the other.

### Steps to reproduce
Component:
```ruby
# frozen_string_literal: true

class RequestComponent < ViewComponent::Base
  def call
    content_tag(:span, request.path, class: 'path') + content_tag(:span, request.fullpath, class: 'fullpath')
  end
end
```

Test file:
```ruby
# frozen_string_literal: true

require "test_helper"

class RequestComponentTest < ViewComponent::TestCase
  test 'should print path and fullpath' do
    with_request_url '/admin/questions' do
      render_inline(RequestComponent.new)

      assert_selector '.path', text: '/admin/questions'
      assert_selector '.fullpath', text: '/admin/questions'
    end
    with_request_url '/admin/questions/1' do
      render_inline(RequestComponent.new)

      assert_selector '.path', text: '/admin/questions/1'
      assert_selector '.fullpath', text: '/admin/questions/1'
    end
    with_request_url '/admin/questions/1?foo=bar' do
      render_inline(RequestComponent.new)

      assert_selector '.path', text: '/admin/questions/1'
      assert_selector '.fullpath', text: '/admin/questions/1?foo=bar'
    end
  end
end
```

### Expected behavior
The test above should pass.

### Actual behavior
The request's `fullpath` property seems to stick from the earlier request. The test fails, since the fullpath still contains the path from the earlier request. This does not reflect the actual behaviour of the app (in a more complex component, of course).

It's easy to work around this issue, by splitting the test up in three different requests, but it might still be good to fix this - or document this issue somewhere.

**Backtrace:**
```
rails t test/components/request_component_test.rb
Running 1 tests in a single process (parallelization threshold is 50)
Run options: --seed 25637

# Running:

F

Failure:
RequestComponentTest#test_should_print_path_and_fullpath [/Users/robbevp/.../test/components/request_component_test.rb:17]:
expected to find visible css ".fullpath" with text "/admin/questions/1" but there were no matches. Also found "/admin/questions", which matched the selector but not all filters. 


rails test test/components/request_component_test.rb:6
```

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**Gem version**: 3.6.0

**Comment by nachiket87** [comment]
Hey @camertron I've created a PR to fix this: https://github.com/ViewComponent/view_component/pull/1893

**Comment by camertron** [comment]
Should be fixed in https://github.com/ViewComponent/view_component/pull/1893
