### ISSUE TITLE
Ability to pass a form object argument into a content block and use it?

### ISSUE THREAD

**Issue by nickjj** [ViewComponent/view_component#1878]
Hello,

I'm not sure if I'm missing something basic but I was trying to build a really simple component for searching. I'm unable to build forms using the default builder with Rails.

Here's a simplified example:

```erb
<%= form_with(url: @url, method: :get, id: "search", data: { controller: "form", action: "input->form#debouncedSubmit", turbo_frame: @turbo_frame, turbo_action: "advance" }) do |form| %>
  <div class="mb-4 relative group">
    <%= search_field_tag :query, @query, placeholder: @placeholder, autofocus: true %>
  </div>
  <div class="space-y-2 mb-6">
    <div class="mt-2">
      <%= content %>
    </div>
  </div>
<% end %>
```

```erb
<%= render SearchComponent.new(url: admin_users_path, turbo_frame: "admin_users", placeholder: "Search users", query: @filter_query) do |form| %>
  <%= form.label :deactivated, class: "inline-flex items-center ml-6" do %>
    <%= check_box_tag :deactivated, "yes", @filter_deactivated, data: { action: "change->search#submit" } %>
    <span>Deactivated</span>
  <% end %>
<% end %>
```

When it comes to displaying the label, it produces this HTML output:

```html
<label for="deactivated_{:class=&gt;&quot;inline-flex items-center ml-6&quot;}">
    &lt;span class=&quot;ml-2 text-slate-600&quot;&gt;Deactivated&lt;/span&gt;
</label>
```

I also tried modifying my component with `<%= form_with(url: @url, builder: ActionView::Helpers::FormBuilder, ...` but it also produced the same output as above.

I saw the known issues around compatibility with Rails form helpers but I'm not sure how to proceed. I didn't want to invest in a custom builder gem since I wanted to use the out of the box Rails form helpers. Is that not an option?

I tried enabling the compatibility patch, but it produces this HTML, it almost worked but not quite:

```html
<label for="deactivated_{:class=&gt;&quot;inline-flex items-center ml-6&quot;}">
  <input type="checkbox" name="deactivated" id="deactivated" value="yes" data-action="change-&gt;search#submit" />
  <span class="ml-2 text-slate-600">Deactivated</span>
</label>
```

I have 6 or 7 search forms that all share this same structure. I didn't want to make a duplicate view component for each one. In this example I could technically use `<label ...>` directly to avoid the Rails helper but in practice other search forms will use select boxes and an assortment of other form helpers.

I thought I might be missing something basic because I'm not sure how to solve this use case. What am I missing? Thanks!

**Comment by camertron** [comment]
Hey @nickjj, thanks for asking about this. As the issue stands now, I'm not sure I have enough information to diagnose the problem. The first thing that jumps out at me is that you're calling `#label` on an instance of `SearchComponent`. Unless I'm mistaken, I think you meant to call `#label` on an instance of `FormBuilder` instead, i.e. the object yielded by `#form_with`. Moreover, I don't see you passing the builder into `SearchComponent.new`, so even if `FormBuilder#label` were being proxied to the builder via `SearchComponent#label`, it has no reference to the builder.

Since the form builder is created inside the component, there's no way to pass it to the parent unless you were to set an instance variable in the `form_with { ... }` block and expose it in `SearchComponent`. Here's how that might look with some of the extra stuff stripped out (although to be honest, I don't advocate for this approach):

```ruby
# app/components/search_component.rb

class SearchComponent < ViewComponent::Base
  attr_reader :form_builder

  def initialize(**kwargs)
    @query = "query"
    @placeholder = "placeholder"
  end
end
```

```erb
<%# app/components/search_component.html.erb %>
<%= form_with(url: @url, method: :get, id: "search", data: { action: "input->form#debouncedSubmit"}) do |form| %>
  <% @form_builder = form %>
  <%# more stuff here %>
<% end %>
```

```erb
<%# app/views/some_controller/index.html.erb %>

<%= render SearchComponent.new(url: "/foo") do |search| %>
  <%= search.form_builder.label :deactivated do %>
    <%= check_box_tag :deactivated, "yes", false, data: { action: "change->search#submit" } %>
    <span>Deactivated</span>
  <% end %>
<% end %>
```

I feel like I have to be missing some context/code here, please advise!

**Comment by nickjj** [comment]
Hi,

Thanks for the reply. The context is you might have a Rails form in a partial but then have 1 or more ViewComponents that you'd like to use within your Rails form block. Ideally you'd like to pass the Rails `form` object into the `content` of the ViewComponent (such as wanting to reference `form.label` in your ViewComponent).

This lets you mostly use partials and sprinkle in a couple of components as needed, all while sticking with the default Rails form builder and no extra dependencies.

**Comment by camertron** [comment]
Ok, that makes sense 👍  Can you post a more complete code example then? I'm not able to follow what you're trying to do given the code you've already posted.

**Comment by nickjj** [comment]
Thanks, sorry about that. I ended up not making a view component for this specific snippet in the end. If another use case pops up where something similar happens I'll provide more details than what was currently provided.
