### ISSUE TITLE
Deprecate the usage of unsupported versions of Ruby and Rails

### ISSUE THREAD

**Issue by reeganviljoen** [ViewComponent/view_component#1897]
# Deprecate the usage of unsupported versions of Ruby and Rails

Currently view_component supports the usage of unsupported versions of ruby (i.e 2,7) as-well as Rails

This will likely cause issues in the  future where developers use view_component on unsupported versions of Ruby or Rails where we will not be able to fully support them as their issues are coming from unsupported versions of Ruby or Rails

## Ruby Life cycle
![image](https://github.com/ViewComponent/view_component/assets/62689748/8fd4b35b-4760-4460-bb46-c9468d6e3c0c)
## Rails Life cycle
![image](https://github.com/ViewComponent/view_component/assets/62689748/a3faa7bb-63dc-4a20-992a-eb4864923dd7)

It is therefore my suggestion that starting with view_component 4 we adopt a ruby and Rails support life cycle aligned with their support dates

**Comment by BlakeWilliams** [comment]
Thanks for putting this together! I like this idea a lot.

> It is therefore my suggestion that starting with view_component 4

I'd also be okay with us adopting this with non-major releases too. e.g. we drop support for unsupported Rails/Ruby's in the next minor version.

**Comment by reeganviljoen** [comment]
@BlakeWilliams I personally would be okay with that, I am just worried about the people who currently use unsupported versions of rails or ruby , but on second thought we can  not be reasonably be expected to maintain unsupported versions of ruby or Rails
