### ISSUE TITLE
Add support for JavaScript in component tests

### ISSUE THREAD

**Issue by unikitty37** [ViewComponent/view_component#1909]
## Feature request
Currently, component tests cannot run JavaScript. This means that components that use JavaScript cannot be tested until they are used in the system, at which point a system test can be used.

However, if the component's JavaScript is incorrect, this is too late to find this out — it would have been more useful to reject the PR implementing the component, rather than merge it and then find out when the component is used that it is wrong.

Would it be possible to add a documented way to use tests in JavaScript? I'm not sure whether simply rendering the preview would be enough, though this would need a way of specifying which preview, and also a way of preventing the test from interacting with the preview chrome. (Is there a way to render the preview without the surrounding chrome, perhaps?)

### Motivation

I would like my employer to be able to require developers to provide tests for components that exercise _all_ functionality of the component, including the JavaScript, so I do not find the components break when I have to use them on a page. Particularly if fixing it then falls to me, rather than the original implementer.

**Comment by reeganviljoen** [comment]
@unikitty37 the best way to do this is to test the components in a system tests with a preview
