### ISSUE TITLE
ViewComponent can't find template for nested slot component

### ISSUE THREAD

**Issue by iamdriz** [ViewComponent/view_component#1977]
### Steps to reproduce

We're using ViewComponent to build a Breadcrumb component in our Rails app:
```
class BreadcrumbComponent < ViewComponent::Base
  renders_many :breadcrumb_items, 'BreadcrumbItemComponent'
  attr_reader :label

  def initialize(label: 'Breadcrumb')
    @label = label
  end

  class BreadcrumbItemComponent < ViewComponent::Base
    attr_reader :label, :href

    def initialize(label: nil, href: nil)
      @label = label
      @href = href
    end
  end
end
```
And for the templates we have the following structure:

![image](https://github.com/ViewComponent/view_component/assets/801252/80e74cdd-02e9-4b9a-b8d9-ea724209bb7b)

But when rendering the component like so:
```
render BreadcrumbComponent.new do |component|
  component.with_breadcrumb_item(label: 'Label', href: '#')
  component.with_breadcrumb_item(label: 'Label', href: '#')
end
```
We're getting an error that it can't find the `BreadcrumbItemComponent` template.

Couldn't find a template file or inline render method for `BreadcrumbComponent::BreadcrumbItemComponent`.

I've moved the template file around into different folders (top-level, the parent component, etc.) but the same error happens... the only way to remove the error is by adding the template with `def call; end` into the `BreadcrumbItemComponent` component so it sees an inline render... but we want to use the template. Does ViewComponent support templates for nested slots?

### System configuration
**Rails version**: 6.1.7.6

**Ruby version**: 3.2.2

**Gem version**: 3.10.0

**Comment by iamdriz** [comment]
This is working now after moving the template under the parent folder (however I did try this before and it didn't work), so not sure what was wrong before... so looks like it's working as expected.

**Comment by Spone** [comment]
I think it's a good opportunity to improve the docs to mention what's the expected file path for nested slot component templates.

Would you like to prepare a PR?
