### ISSUE TITLE
Component renders "" (blank) when an error is raised during the render phase

### ISSUE THREAD

**Issue by mjacobus** [ViewComponent/view_component#1981]
### Steps to reproduce

Render a component from a controller

```ruby
class MyBrokenComponent < ViewComponent::Base
  erb_template <<-ERB
    foo <% raise_an_error %> bar
  ERB

  def raise_an_error
    raise "an error"
  end
end

class MyController < ActionController::Base
  def show
    render MyBrokenComponent.new
  end
end
```

### Expected behavior

I expected to see the rails error page.

### Actual behavior

A blank page.

### A few things worth noting

1) If just one of the components raises an error, only that component will be blank. The rest of the page will work:

```erb
<!-- my_page_component.html.erb -->
<%= render SpanComponent.new("one") %>
<%= render MyBrokenComponent.new %>
<%= render SpanComponent.new("two") %>
```

The page will render:

```html
<span>one</span>
<span>two</span>
```

2) If MyBrokenComponent raises during in the initializer, the page will be blank.

```erb
<!-- my_page_component.html.erb -->
<%= render SpanComponent.new("one") %>
<%= render MyBrokenComponent.new %>
<%= render SpanComponent.new("two") %>
```

3) If the component rendered by the controller raises an error in the initializer, the expected error page will be displayed. 

```ruby
class MyBrokenComponent < ViewComponent::Base
  erb_template <<-ERB
    foo bar
  ERB

  def initialize
    raise "an error"
  end
end

class MyController < ActionController::Base
  def show
    # the rails error page will be rendered
    render MyBrokenComponent.new 
  end
end
```

So all of that, makes me believe that the error suppressing is happening during the rendering phase.

**Backtrace**:

### System configuration

**Rails version**: `Rails 7.0.8`
**Ruby version**: `ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-darwin21]`
**Gem version**: `view_component (3.10.0)`,  `view_component (3.5.0)`, `view_component (3.0.0)` (without the `erb_template` syntax.

**Comment by reeganviljoen** [comment]
@mjacobus if you are able to add failing tests in a pr it would help a lot, otherwise someone will be able to do it

**Comment by mjacobus** [comment]
@reeganviljoen noted! 👍🏻 I will dig some more, and I come back to it.

**Comment by mjacobus** [comment]
I found the culprit. That is https://github.com/newrelic/newrelic-ruby-agent.

It overrides the render method:

https://github.com/newrelic/newrelic-ruby-agent/blob/2968b6ccda8f4e8220e0a666cd72f52add3e3acc/lib/new_relic/agent/instrumentation/view_component/prepend.rb#L9-L11

Rescue exceptions and don't raise again:

https://github.com/newrelic/newrelic-ruby-agent/blob/2968b6ccda8f4e8220e0a666cd72f52add3e3acc/lib/new_relic/agent/instrumentation/view_component/instrumentation.rb#L17-L21

**Comment by reeganviljoen** [comment]
@mjacobus i also use new relic + view_component I will issue a bug report if you haven't already

**Comment by mjacobus** [comment]
Thank you @reeganviljoen.

This is the PR that introduced this behavior: https://github.com/newrelic/newrelic-ruby-agent/pull/2367/files#r1463895980

**Comment by mjacobus** [comment]
Here's a PR that should fix the issue: https://github.com/newrelic/newrelic-ruby-agent/pull/2410

**Comment by reeganviljoen** [comment]
@mjacobus what a legend, can't wait for them to fix it 🙏

**Comment by mjacobus** [comment]
For the record, we can disable view component instrumentation with the `instrumentation.view_component` option.

```yaml
# config/newrelic.yml
common: &default_settings
  # [...]
  instrumentation.view_component: disabled

**Comment by kinduff** [comment]
@mjacobus You are a legend, thank you so much!
