### ISSUE TITLE
undefined method `rstrip!' for #<struct ViewComponent::InlineTemplate::Template

### ISSUE THREAD

**Issue by abr-storm** [ViewComponent/view_component#2013]
Hi, apologies for not opening a PR - the devcontainer configuration failed when I tried to load it (MacOS + Docker Desktop 4.22)

I'm running into issues with trailing whitespace and inline template handlers. Firstly, if you have a `strip_trailing_whitespace` and an `erb_template` in the same component, rendering will raise an error. You can see this happening with `SimpleInlineComponent` and `NestedComponent` in my example app.

This next part might be user error, but the reason I was trying to add these `strip_trailing_whitespace` calls was due to the fact stray newline characters are being added into the markup when my `NestedComponent` is rendered. I would appreciate any guidance on why this is happening and what I can do to fix it

Cheers

### Steps to reproduce
https://github.com/abr-storm/view-component-newlines

### Expected behavior
No error raised when visiting `/simple`

### Actual behavior
Error is raised

**Backtrace**:
```
undefined method `rstrip!' for #<struct ViewComponent::InlineTemplate::Template source="<div>Fooo</div>\n", language="erb", path="/Users/alex/src/view-component-newlines/app/components/simple_inline_component.rb", lineno=4>
```

### System configuration
**Rails version**:
7.1.3

**Ruby version**:
3.2.2

**Gem version**:
`main` (3.11.0)

**Comment by reeganviljoen** [comment]
@abr-storm thank you fir the bug report, we really appreciate all the details you added, I will see if I can see what the issue is, maybe one of the maintaners can have an idea, cc @joelhawksley @Spone @boardfish @camertron @joelhawksley

**Comment by Spone** [comment]
@reeganviljoen can you try opening a PR with a failing test?

**Comment by reeganviljoen** [comment]
@Spone I can find some time this weekend

**Comment by reeganviljoen** [comment]
@Spone failing tests have been added 👍
