### ISSUE TITLE
Add documentation for how to use view_component with ruby2html

### ISSUE THREAD

**Issue by sebyx07** [ViewComponent/view_component#2071]
## Feature request
Add documentation to use view_component with ruby2html + maybe configuration for generators

I already have a documentation for view_component in https://github.com/sebyx07/ruby2html?tab=readme-ov-file#with-viewcomponents

### Motivation

make it easier for people to write the frontend in pure ruby

**Comment by reeganviljoen** [comment]
We try to keep our documentation focused on the library iteself, you can however open a pull request to link it on the [extensions page](https://viewcomponent.org/resources.html#viewcomponent-extensions)

**Comment by camertron** [comment]
Hey @sebyx07, to echo what @reeganviljoen said, we like to keep our docs focused on the library itself. I would also say that using ruby2html with ViewComponent is pretty straightforward, since I believe you'd just define a `call` method and stick your template in there, right? Eg.

```ruby
class MyComponent < ViewComponent::Base
  def call
    div class: "foo" do
      ...
    end
  end
end
```

**Comment by reeganviljoen** [comment]
@camertron @sebyx07 I am closing this as completed as it seems this has been solved.
