### ISSUE TITLE
ActionView::Template::Error: undefined method `identifier' for class LinkComponent

### ISSUE THREAD

**Issue by navidemad** [ViewComponent/view_component#2106]
### Steps to reproduce
Having newrelic_rpm enable and view_component on his latest version.

### Expected behavior
No error

### Actual behavior
ActionView::Template::Error: undefined method `identifier' for class LinkComponent

### System configuration
ruby (3.3.5)
rails (7.2.1)
view_component (3.15.0)
newrelic_rpm (9.13.0)

### Related
https://github.com/ViewComponent/view_component/commit/451543a53f3c7c04036eb6109ac716511f3dcfc3#diff-b69c75ffd85596e0b5fca1327059ecf3b2930f3f77004c78a268fa85e8ec8d9eL601
https://github.com/newrelic/newrelic-ruby-agent/issues/2869

**Comment by rickychilcott** [comment]
Ran into the same here. Thanks for tracking it down to NewRelic enabled + ViewComponent 3.15.0 @navidemad!

**Comment by joelhawksley** [comment]
@navidemad thanks for the report. That method was marked as `private` and should not have been depended on: https://github.com/ViewComponent/view_component/compare/v3.14.0...v3.15.0#diff-b69c75ffd85596e0b5fca1327059ecf3b2930f3f77004c78a268fa85e8ec8d9eL601

**Comment by jcoyne** [comment]
It's possible to workaround this problem by adding an initializer that restores the method until newrelic gets their gem fixed:
```ruby
# config/initializers/newrelic_monkeypatch.rb

# workaround for bug https://github.com/newrelic/newrelic-ruby-agent/issues/2869
class ViewComponent::Base
  def self.identifier
    source_location
  end
end
```

**Comment by joelhawksley** [comment]
This should be addressed by https://github.com/ViewComponent/view_component/releases/tag/v3.15.1 ❤

**Comment by joelhawksley** [comment]
👋🏻 I'm [proposing](https://www.github.com/viewcomponent/view_component/pull/2153) that we make `.identifier` public ❤
