### ISSUE TITLE
WARNING: The Class.identifier in logs

### ISSUE THREAD

**Issue by m7madmagdy** [ViewComponent/view_component#2122]
WARNING: The Class.identifier is undocumented and was meant for internal framework usage only. As it is no longer used by the framework it will be removed in a coming non-breaking ViewComponent release.

### System configuration
**Rails version**: 7.2

**Ruby version**: 3.3.5

**Gem version**: 3.15.1

**Comment by joelhawksley** [comment]
@m7madmagdy this warning is intentional. If you are receiving it, you should look to see what is calling `identifier`.
