### ISSUE TITLE
Access request within SlotComponent instance

### ISSUE THREAD

**Issue by scottbarrow** [ViewComponent/view_component#409]
## Feature request
https://github.com/github/view_component/pull/59 added context and access to the request object within the component, however this does not seem to extend to SlotComponent.
I would like to propose this change to SlotComponents also 

### Motivation

I would like to use an active nav anchor tag in a NavItem slot within a NavBarComponent, by using the request to determine the `current_page?` Currently I having to work around this by wrapping the SlotComponent instance in a method in the parent Component and calling the method from the template.
To me the SlotComponents should have access to the same helpers and view context that the parent components currently provide.

I will attempt a PR of this myself if there's acceptance and motivation to do so.

**Comment by joelhawksley** [comment]
@scottbarrow 👍 sounds fantastic, let me know if you need a 🍐 for your PR 😄

**Comment by scottbarrow** [comment]
still hoping to get to this, I will attempt to this weekend

**Comment by joelhawksley** [comment]
Closing as stale.
