### ISSUE TITLE
It's not clear if the `render?` method should be public or private

### ISSUE THREAD

**Issue by BlakeWilliams** [ViewComponent/view_component#486]
This came up in a discussion when reviewing a few PR's, it's not clear if `render?` should be a public or a private method. This means we end up with some components defining it publicly, and other methods defining it privately with no real consistency.

I think this has a few side-effects
* There's no clear best practice
* External libraries, and view component itself can't rely on the method being publicly accessible
* People end up having debates about what the visibility should be

One idea was to replace the `render?` method with a DSL method that allows the library to control visibility. Inspired by Rails' `before_action`, we could potentially do something like:

```ruby
skip_render_if :method_or_predicate
render_if :method_or_predicate
```

This takes us one step away from view component being PORO based, but does solve some of the above problems.

**Comment by yoones** [comment]
Looking at the source code of `ViewComponent::Base` I see that `#render?` is public, so IMO we should keep it public in our components too.
