### ISSUE TITLE
React like Error Boundaries

### ISSUE THREAD

**Issue by francescobbo** [ViewComponent/view_component#517]
## Feature request

It would be really awesome to be able to capture errors in production and render fallback templates, instead of having a whole page break.

In React, one would create a component that wraps another, define a `componentDidCatch` method, and define what to render when something happens.

I thought that the React approach would be easily ported:

```ruby
class ErrorBoundaryComponent < ViewComponent::Base
  def call
    content

  rescue => exc
    # Report to some service
    Raven.capture_exception(exc)
    # possibly render a partial here instead of inlining
    "Something went wrong."
  end
end
```
and then using it like this:

```erb
<%= render(ErrorBoundaryComponent.new) do %>
  <%= render(InnerComponent.new(abc: 'test')) %>
<% end %>
```

The above however does not work, and I believe the reason is that inner components are rendered before parents, so `ErrorBoundaryComponent` `rescue` block is useless.

That however is not what I would like to have in a Rails app. Here's what I imagined:

```ruby
class FallibleComponent < ViewComponent::Base
  rescue_from SomeMoreSpecificError, with: :handle_specific_error
  rescue_from StandardError, with: :handle_errors

  def handle_errors
    # Report to some service
    Raven.capture_exception(exc)
    # possibly render a partial here instead of inlining
    "Something went wrong."
  end

  [...]
end
```

Then refactor that into a Mixin, and use everywhere.

If you believe this can be useful, I might give a shot at preparing a PR myself :)

### Motivation

Unpredictable production errors happen from time to time. If a component represents a negligible part of a page (say a widget in a sidebar, a footer), it can be really annoying for it to blow up (500) what might be a critical part of an application.

**Comment by BlakeWilliams** [comment]
👋 This sounds like an interesting idea, and likely something that we'd want to support in view components. Would you mind opening up a PR for this behavior so we can continue the discussion?

**Comment by joelhawksley** [comment]
Closing as stale.

**Comment by ozzyaaron** [comment]
I know its closed but for anybody else looking for this type of thing the way we're doing it is just to override the `render_in` method on base component as we're finding we want different error boundary responses depending on the type of component 

e.g. 

```
class FormFieldWithErrorBoundary < ApplicationComponent
  ...
  render_in(*)
    super
  rescue => e
     ... handle error, send to logging, whatever ...

     # We use a component, but whatever 
     render(ErrorBannerComponent.new(message: ..)
  end
end
```

For things like lists for instance if you wanted to not have 1 row kill things we catch them at the table level rather than per row to reduce error notifications in catastrophic cases and put a banner above the table but notify about which row/s failed so we can debug later. 

Not sure if there are better ways but this is working for us.
