### ISSUE TITLE
Passing context to slots and subcomponents

### ISSUE THREAD

**Issue by rewritten** [ViewComponent/view_component#545]
## Feature request

Passing extra context from the component template to slots, that can be used back in the slot content. For instance, when iterating a collection, be able to use the current item in the slot content.

```rb
class MyComponent < ViewComponent::Base
  render_one :display
end
```

```erb
<!-- my_component.erb -->
<div class="my-component">
  <%= display.with(object_id).content %>
</div>
```

```erb
<!-- should render the object_id of the component in a span. -->
<%= render MyComponent.new do |c| %>
  <% c.display do |arg| %>
    <span><%= arg %></span>
  <% end %>
<% end %>
``` 

### Motivation

One of the main use cases for components in the projects I usually work on is tables, with lots of features that repeat across all tables. 

Something I would like to be using is like (using slots v2):
```erb
  <!-- my_view.html.erb -->
  <%= render Admin::TableComponent.new(items: cases) do |c| %>
    <% c.column label: 'Case #', width: 1 do |case| %>
      <%= case.public_id %>
    <% end %>
    <% c.column label: 'Field 1', width: 4, sortable: 'f1' do |case| %>
      <%= case.field_1 %>
    <% end %>
    <% c.column label: 'Field 1', width: 4, filterable: 'f2_cont' do |case| %>
      <strong><%= case.field_2 %></strong>
    <% end %>
  <% end %>
```

This would be my attempt for the component's template (skipping the extra features).

I'm using `<%= col.with(item).content %>` to imply where the item is passed to be used as block parameter.

```erb
<div class='table-responsive'>
  <table class='table'>
    <thead>
      <tr>
        <% columns.each do |col| %>
          <th>
            <% if col.sortable %>
              <% render Table::SortableHeader.new(label: col.label, current_sort: request.params[:sort]) %>
            <% else %>
              <%= col.label %>
            <% end %>
          </th>
        <% end %>
      </tr>
      <% if columns.any?(&:filterable) %>
       <tr>
         ... render filters...
       </tr>
     <% end %>
    </thead>

    <tbody>
      <% items.each do |item| %>
        <tr>
          <% columns.each do |col| %>
            <td><%= col.with(item).content %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
     <tr>
      <td colspan="<%= columns.count %>">
        <%= render Table::Pagination(items: items, current_page: request.params[:page]) %>
      </td>
     </tr>
    </tfoot>
  </table>
</div>
```

So the outcome would use each of the columns once to fill the thead (ignoring the block) and N times for the tbody

This is similar to how tables are built in ActiveAdmin (https://activeadmin.info/3-index-pages/index-as-table.html) Ember's light-tabe (http://adopted-ember-addons.github.io/ember-light-table/) and DataTables (these are the most appropriate examples to show what I mean: https://datatables.net/examples/basic_init/data_rendering.html https://datatables.net/examples/ajax/deep.html)

**Comment by rewritten** [comment]
Also https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots

**Comment by BlakeWilliams** [comment]
👋 Thanks for opening this issue! Supporting the ability to make tables with view components is something that we want to support given how common the pattern is.

To help us completely understand the problem and potential solutions here, could you open a PR with a failing test case?

**Comment by rewritten** [comment]
@BlakeWilliams there you go :) I hope I can help on that

**Comment by BlakeWilliams** [comment]
Thanks! I'll look at it sometime this week and we can chat about it in the PR thread. :)

**Comment by joelhawksley** [comment]
Closing as stale.
