### ISSUE TITLE
content not available inside slotted component

### ISSUE THREAD

**Issue by dkniffin** [ViewComponent/view_component#612]
### Steps to reproduce
```ruby
class ParentComponent < ViewComponent::Base
  include ViewComponent::SlotableV2

  renders_many :children, ChildComponent

  def children_have_content?
    children.any?(&:has_content?)
  end
end

class ChildComponent < ViewComponent::Base
  def has_content?
    !content.nil?
  end
end
```

### Expected behavior
Calling `ParentComponent#children_have_content?` should return the correct value based on whether the children have `content` defined

### Actual behavior
`ParentComponent#children_have_content?` returns `nil`. It looks like this is because `content` inside the child component is `nil` at this point, even though later when being called in the template, it's not nil. 

Calling `to_s` inside of the `any?` seems to be a workaround for this. I suspect it has something to do with the order of when the child component gets rendered vs when I'm calling these methods. If the child hasn't been rendered yet, `content` doesn't seem to be able to resolve correctly.

This might be part of a solution?
```ruby
module ViewComponent
  class SlotV2
    # ...
    def content
      to_s
    end
    # ...
  end
end
```
That makes `child.content` accessible from the parent component, so I could define the method there differently and get it to work. However, I'd like to encapsulate the logic inside the child component, so it should be able to access it's own `content`.

### System configuration
**Rails version**: `6.0.3.4`

**Ruby version**: `ruby 2.7.2p137`

**Gem version**: `2.25.1`

**Comment by joelhawksley** [comment]
@dkniffin I'm not sure why this was never triaged. Would you be willing to provided a failing test for this bug?

**Comment by dkniffin** [comment]
@joelhawksley https://github.com/ViewComponent/view_component/pull/1668
