### ISSUE TITLE
ViewComponent references on other sites

### ISSUE THREAD

**Issue by joelhawksley** [ViewComponent/view_component#630]
## Feature request

It could be interesting to see about getting ViewComponent some references from other industry sites.

Two places come to mind:

- https://www.componentdriven.org
- https://storybook.js.org

### Motivation

It's likely not general knowledge that ViewComponent enables modern UI development techniques in Rails.

**Comment by jonspalmer** [comment]
I can help figure out how to connect the dots with StorybookJS.

**Comment by phacks** [comment]
We have a working (though very new) ViewComponents/Storybook setup at my company. Happy to talk/write about it it that helps!

**Comment by joelhawksley** [comment]
@jonspalmer @phacks that would be great!

**Comment by phacks** [comment]
Took me a while, but I just published a step-by-step tutorial that explains how to create your first ViewComponent, add it to Storybook, and deploy the result to production: https://orbit.love/blog/building-a-component-library-in-rails-with-storybook

Hope that helps folks get started, and thank you @joelhawksley and @jonspalmer for the respective gems that made all this possible!
