### ISSUE TITLE
Error message helpfulness

### ISSUE THREAD

**Issue by joelhawksley** [ViewComponent/view_component#896]
## Feature request

As a consumer of the ViewComponent framework, I want to receive actionable feedback when an error is raised. For every error message, I should be provided with directions on how it might be resolved, and if relevant, a link to more documentation. 

As part of this ticket, we should add all error messages to the API documentation.

### Motivation

In my research on writing technical documentation, several resources recommended providing documentation for all framework-defined error messages, including the actual text of the message, so that if people Google for the message, they are lead to the documentation site.

**Comment by Spone** [comment]
How do you want to proceed? We can prepare a list of error messages existing in the source code, like this:

> #### ViewComponentsSystemTestController must only be called in a test environment
>
> -------
> 
> #### Component preview `[path]` not found.
> 
> -------
> 
> #### It looks like a block was provided after calling `with_content` on `[ComponentClass]`, which means that ViewComponent doesn't know which content to use.
> 
> To fix this issue, use either `with_content` or a block.
>
> -------
>
> #### `#controller` can't be used during initialization, as it depends on the view context that only exists once a ViewComponent is passed to the Rails render pipeline.
>
> It's sometimes possible to fix this issue by moving code dependent on `#controller` to a `#before_render` method: https://viewcomponent.org/api.html#before_render--void.
>
> -------
>
> ...

Then, we can review which error messages need to be improved.

Finally, do we add them to the documentation site manually? Can we leverage YARD for this?

**Comment by joelhawksley** [comment]
@Spone I think we should use YARD for this, yes. We would have a custom error class for each possible error then have YARD docs for each class.

**Comment by joelhawksley** [comment]
Closing as done- I'm satisfied with the updates I've made.
