### ISSUE TITLE
Add paved path for unit testing components with behaviors

### ISSUE THREAD

**Issue by joelhawksley** [ViewComponent/view_component#904]
### Problem statement

> How have y'all at Github approached testing view components that have an interactive component to them? We've mainly been unit testing each view component we add and then writing feature specs for browser interactions, but I'm wondering if there is a better way to approach it - RailsConf Q&A

### Proposed solution

In Primer ViewComponents, we use system tests powered by cuprite and ViewComponent Previews for testing behaviors. As this approach matures, we should aim to move of much of it as possible into ViewComponent.

**Comment by joelhawksley** [comment]
@edwinthinks thank you for your interest!

I could imagine us implementing a new base test case for browser-based tests. Something like Rails System tests, but catered to ViewComponent.

I could imagine this functionality being driven by some sort of `render_in_browser` test helper that accepts a component instance.

**Comment by edwinthinks** [comment]
Thanks that is helpful context.

Though I'am wondering how something like the `render_in_browser` would work in practice? Specifically, how would it handle the layout (which probably contains the snippets of code to load the JS for the interaction). My initial idea was to accept a layout as a parameter that would generate the corresponding HTML in a temporary file and have capybara load it up. Thoughts?

Wondering if you'd like to brainstorm and pair on this in the next few weeks?

**Comment by edwinthinks** [comment]
Opened up https://github.com/github/view_component/pull/1061 which I think is close-ish to what you were saying @joelhawksley. 

It does appear to work in some situations but I'am not entirely sure what the ideal way to handle assets is and also to make this compatible for Rails versions lower than 6.1. 

Excited to see this through and see if it helps others with testing components easier :)

**Comment by jonspalmer** [comment]
Commented in #1061 but I feel pretty strongly that these kinds of tests should be a flavor of system test and leverage all the existing machinery for running system tests against multiple browsers, Selenium Grid etc. Problems with assets, differences with webpacker or not etc are already well solved in system tests. It would also encourage using a "production layout" for the css/js. What we need to make these tests simple to write is some  mechanism for defining the html endpoint (we do this with previews) and a likely some helpers to dry up the test declarations (ie something that auto 'gets' the html content for a named VC

**Comment by edwinthinks** [comment]
Thanks, @jonspalmer; 

I'll be honest I don't have a lot of experience with system tests as it compares to browser tests. *Could you send me some resources to explain the difference? Thanks!* But if using system tests is going to simply things going forward then I think that is a good route to go.

On that note, are there any concerns about relying on system tests for those applications that don't already use it? Speaking from my project at work; we use browser tests but not system tests yet.

**Comment by jonspalmer** [comment]
I'm very late to comment back on this thread. Rails System test work well "out of the box" https://guides.rubyonrails.org/testing.html#system-testing Looks like you found that and the recent merge of the PR looks awesome.

**Comment by joelhawksley** [comment]
Glad to hear from you @jonspalmer ❤️ 

I'll take your note as sign enough that we an close this one!
