### ISSUE TITLE
Using #with_content on pass through slots throws 'undefined method `with_content` for nil:NilClass'

### ISSUE THREAD

**Issue by dkimot** [ViewComponent/view_component#918]
In lieu of a pr I have a suspected cause, detailed at the end of this issue.

### Steps to reproduce

Using `with_content` on a pass through slot with no arguments, like what is documented [here](https://viewcomponent.org/guide/slots.html#with_content).

### Expected behavior

The content argument passed into `with_content` is rendered as the slot.

### Actual behavior

The error undefined method `with_content` for nil:NilClass is raised.

### System configuration
**Rails version**:
6.1.3.1

**Ruby version**:
3.0.0

**Gem version**:
2.31.1

#### Suspected cause

`SlotableV2`'s defined method for a slot, seen [here](https://github.com/github/view_component/blob/main/lib/view_component/slotable_v2.rb#L70), checks to see if the slots caller passed in args or a block and uses that to determine the response.

If you call the slot without args or a block it's value is the result of `get_slot(slot_name)` which is the value nil returned on [line 202](https://github.com/github/view_component/blob/main/lib/view_component/slotable_v2.rb#L202) of that file.

If I pass args into the slot `<% modal.header(classes: nil).with_content(title) %>` it renders the slot correctly.

#### Potential solution

I'm happy to open a PR to fix this, but I'm not sure what the solution should be. To get access to `with_content` the slot's method will need to return an instance of `SlotV2` whether or not arguments/a block are passed in. I don't know if that means the parts of `set_slot responsible for initializing the slot need to be extracted to a method both `get_slot` and `set_slot` call or if `get_slot` should just be removed completely. I could also be way off base with my proposed solution.

**Comment by dkimot** [comment]
I realized that this wasn't occurring on collection slots when passing in content to the singular form of that slot (ie a `menu_item` of the slot `menu_items). I went and checked and found that the singular version of a collection slot always returns the result of `set_slot`, see [here](https://github.com/github/view_component/blob/main/lib/view_component/slotable_v2.rb#L126).

**Comment by jonspalmer** [comment]
I ran into this exact problem working on https://github.com/jonspalmer/view_component_storybook/pull/68
I like the proposed solution a great deal.

**Comment by jonspalmer** [comment]
@BlakeWilliams Thinking about this a bit more I'm not convinced that your solution will work. I'm worried that it forces all slots to have to be set before they are read. Otherwise any optional slot will get instantiated incorrectly when it's read at render time. 

A few other thoughts on solutions:
1. Add a magic `context` argument @joelhawksley and I touched on this here: https://github.com/github/view_component/pull/1008#issuecomment-882874968
2. Could we add a "bang" version of the slot method that was always the `set_slot` behavior and never a getter? It's a little quirky but not totally inconsistent with bang methods mutating state

**Comment by joelhawksley** [comment]
This has been fixed with the new Slots API that split out the getter and setter ❤️
