### ISSUE TITLE
Wrong number of arguments in slot initialize

### ISSUE THREAD

**Issue by BigBigDoudou** [ViewComponent/view_component#931]
### Steps to reproduce

Create this component:

```ruby
class ListComponent < ViewComponent::Base
  include ViewComponent::SlotableV2
  renders_many :items, "ListItemComponent"

  def call
    tag.ul do
      items.each { |item| concat(item) }
    end
  end

  class ListItemComponent < ViewComponent::Base
    def initialize(value: nil)
      @value = value
    end

    # we want the same behaviour than Rails `tag`
    # i.e. be able to call `tag.div("Hello World")` and `tag.div { "Hello World" }`
    def call
      tag.li(@value || content)
    end
  end
end
```

Then use it with:

```ruby
render(AbstractComponent::ListComponent.new) do |list|
  list.item(value: "Hello World")
  list.item do
    tag.span("Hello World")
  end
end
```

Ensure it works.

Now, replace the keyword argument `value` by a simple argument:

```ruby
def initialize(value = nil)
  @value = value
end
```

and

```ruby
list.item("Hello World")
```

You should have an error:

```
ActionView::Template::Error (wrong number of arguments (given 2, expected 1))
    1: <% if ViewComponent::Base.render_monkey_patch_enabled || Rails.version.to_f >= 6.1 %>
    2:   <%= render(@render_args[:component], @render_args[:args], &@render_args[:block])%>
    3: <% else %>
    4:   <%= render_component(@render_args[:component], &@render_args[:block])%>
    5: <% end %>
```

This second argument is `{}` (due to `&@render_args[:block]`?). So the workaround is:

```ruby
def initialize(value = nil, _)
  @value = value
end
```

### Expected behavior

We should be able to use arguments in slots.

### Actual behavior

Raises error `ActionView::Template::Error (wrong number of arguments (given 2, expected 1))`.

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: ruby 2.6.6p146

**Gem version**: 2.31.1

**Comment by BlakeWilliams** [comment]
@BigBigDoudou thanks for the report!

If possible could you open a PR with a failing test?

**Comment by BigBigDoudou** [comment]
@BlakeWilliams So I've tried to write some tests to point out the problem but... tests work!
https://github.com/BigBigDoudou/view_component/commit/353dace45c919c6355b8313499ba12939f21a987

May be it is related to ruby version, since I switch to 2.7 when I'm on the gem (versus 2.6.6 on my application). I'll try more tests.

**Comment by joelhawksley** [comment]
Closing as we now only support ruby 2.7+.
